#pragma once
#include "SimDll13.h"

namespace Sim
{

	class SIMDLL_EXPORTS AD135 : public Model
	{
	public:
		AD135();
		~AD135();
		void SetModelParameters();
		void InitializeModelVars();

		void ModelDerivatives(int iCol);
		SIM_DATA* Base(){ return &m_sdBase; }
		SIM_DATA* ConstBase(){ return &m_sdConstBase; }
		char* Name(){ return "AD135";}
		int StateSize(){ return 317;}
		int NonStateSize(){ return 865;}
		int ConstSize(){ return 178;}
		SIM_DATA YScale(){ return m_sdscale;}
		int NumCustIcTabs(){ return 4;}

		//FUNCTIONS


		//SUBMODELS


	private:
		SIM_DATA m_sdBase;
		//define NS_VARS here
		SIM_DATA m_sdMW;           //NS_VAR [MW] [User] []
		SIM_DATA m_sdCPW;           //NS_VAR [CPW] [User] []
		SIM_DATA m_sdMW2;           //NS_VAR [MW2] [User] []
		SIM_DATA m_sdCPW2;           //NS_VAR [CPW2] [User] []
		SIM_DATA m_sdMW3;           //NS_VAR [MW3] [User] []
		SIM_DATA m_sdCPW3;           //NS_VAR [CPW3] [User] []
		SIM_DATA m_sdPDOT;           //NS_VAR [PDOT] [User] []
		SIM_DATA m_sdCUT;           //NS_VAR [CUT] [User] []
		SIM_DATA m_sdRAMP;           //NS_VAR [RAMP] [User] []
		SIM_DATA m_sdTEMP;           //NS_VAR [Average Fuel Temperature] [Performance] [C]
		SIM_DATA m_sdalpha;           //NS_VAR [alpha] [User] []
		SIM_DATA m_sdkinvis;           //NS_VAR [kinvis] [User] []
		SIM_DATA m_sdkinvis1;           //NS_VAR [kinvis1] [User] []
		SIM_DATA m_sdkinvis2;           //NS_VAR [kinvis2] [User] []
		SIM_DATA m_sdkinvis3;           //NS_VAR [kinvis3] [User] []
		SIM_DATA m_sdFuelDen;           //NS_VAR [Fuel Density] [Thermal Parameters$] [kg/m^3]
		SIM_DATA m_sdEM;           //NS_VAR [EM] [User] []
		SIM_DATA m_sdELM;           //NS_VAR [ELM] [User] []
		SIM_DATA m_sdELM2;           //NS_VAR [ELM2] [User] []
		SIM_DATA m_sdELM3;           //NS_VAR [ELM3] [User] []
		SIM_DATA m_sdAK;           //NS_VAR [AK] [User] []
		SIM_DATA m_sdAK2;           //NS_VAR [AK2] [User] []
		SIM_DATA m_sdTCA1;           //NS_VAR [TCA1] [User] []
		SIM_DATA m_sdTCA2;           //NS_VAR [TCA2] [User] []
		SIM_DATA m_sdTCA3;           //NS_VAR [TCA3] [User] []
		SIM_DATA m_sdTCA4;           //NS_VAR [TCA4] [User] []
		SIM_DATA m_sdTCA5;           //NS_VAR [TCA5] [User] []
		SIM_DATA m_sdTCA6;           //NS_VAR [TCA6] [User] []
		SIM_DATA m_sdTCA7;           //NS_VAR [TCA7] [User] []
		SIM_DATA m_sdTCA8;           //NS_VAR [TCA8] [User] []
		SIM_DATA m_sdTCA9;           //NS_VAR [TCA9] [User] []
		SIM_DATA m_sdTCA10;           //NS_VAR [TCA10] [User] []
		SIM_DATA m_sdTCAL1;           //NS_VAR [TCAL1] [User] []
		SIM_DATA m_sdTLA1;           //NS_VAR [TLA1] [User] []
		SIM_DATA m_sdTLA2;           //NS_VAR [TLA2] [User] []
		SIM_DATA m_sdTLA3;           //NS_VAR [TLA3] [User] []
		SIM_DATA m_sdTLA4;           //NS_VAR [TLA4] [User] []
		SIM_DATA m_sdTLA5;           //NS_VAR [TLA5] [User] []
		SIM_DATA m_sdTLA6;           //NS_VAR [TLA6] [User] []
		SIM_DATA m_sdTLA7;           //NS_VAR [TLA7] [User] []
		SIM_DATA m_sdTLA8;           //NS_VAR [TLA8] [User] []
		SIM_DATA m_sdTLA9;           //NS_VAR [TLA9] [User] []
		SIM_DATA m_sdTLA10;           //NS_VAR [TLA10] [User] []
		SIM_DATA m_sdTLAL1;           //NS_VAR [TLAL1] [User] []
		SIM_DATA m_sdTKW1;           //NS_VAR [TKW1] [User] []
		SIM_DATA m_sdTKF01;           //NS_VAR [TKF01] [User] []
		SIM_DATA m_sdTKF1;           //NS_VAR [TKF1] [User] []
		SIM_DATA m_sdTHDIFF1;           //NS_VAR [THDIFF1] [User] []
		SIM_DATA m_sdbta1;           //NS_VAR [bta1] [User] []
		SIM_DATA m_sddynvis1;           //NS_VAR [dynvis1] [User] []
		SIM_DATA m_sdTCA21;           //NS_VAR [TCA21] [User] []
		SIM_DATA m_sdTCA22;           //NS_VAR [TCA22] [User] []
		SIM_DATA m_sdTCA23;           //NS_VAR [TCA23] [User] []
		SIM_DATA m_sdTCA24;           //NS_VAR [TCA24] [User] []
		SIM_DATA m_sdTCA25;           //NS_VAR [TCA25] [User] []
		SIM_DATA m_sdTCA26;           //NS_VAR [TCA26] [User] []
		SIM_DATA m_sdTCA27;           //NS_VAR [TCA27] [User] []
		SIM_DATA m_sdTCA28;           //NS_VAR [TCA28] [User] []
		SIM_DATA m_sdTCA29;           //NS_VAR [TCA29] [User] []
		SIM_DATA m_sdTCA210;           //NS_VAR [TCA210] [User] []
		SIM_DATA m_sdTCAL2;           //NS_VAR [TCAL2] [User] []
		SIM_DATA m_sdTLA21;           //NS_VAR [TLA21] [User] []
		SIM_DATA m_sdTLA22;           //NS_VAR [TLA22] [User] []
		SIM_DATA m_sdTLA23;           //NS_VAR [TLA23] [User] []
		SIM_DATA m_sdTLA24;           //NS_VAR [TLA24] [User] []
		SIM_DATA m_sdTLA25;           //NS_VAR [TLA25] [User] []
		SIM_DATA m_sdTLA26;           //NS_VAR [TLA26] [User] []
		SIM_DATA m_sdTLA27;           //NS_VAR [TLA27] [User] []
		SIM_DATA m_sdTLA28;           //NS_VAR [TLA28] [User] []
		SIM_DATA m_sdTLA29;           //NS_VAR [TLA29] [User] []
		SIM_DATA m_sdTLA210;           //NS_VAR [TLA210] [User] []
		SIM_DATA m_sdTLAL2;           //NS_VAR [TLAL2] [User] []
		SIM_DATA m_sdTKW2;           //NS_VAR [TKW2] [User] []
		SIM_DATA m_sdTKF02;           //NS_VAR [TKF02] [User] []
		SIM_DATA m_sdTKF2;           //NS_VAR [TKF2] [User] []
		SIM_DATA m_sdTHDIFF2;           //NS_VAR [THDIFF2] [User] []
		SIM_DATA m_sdbta2;           //NS_VAR [bta2] [User] []
		SIM_DATA m_sddynvis2;           //NS_VAR [dynvis2] [User] []
		SIM_DATA m_sdTCA31;           //NS_VAR [TCA31] [User] []
		SIM_DATA m_sdTCA32;           //NS_VAR [TCA32] [User] []
		SIM_DATA m_sdTCA33;           //NS_VAR [TCA33] [User] []
		SIM_DATA m_sdTCA34;           //NS_VAR [TCA34] [User] []
		SIM_DATA m_sdTCA35;           //NS_VAR [TCA35] [User] []
		SIM_DATA m_sdTCA36;           //NS_VAR [TCA36] [User] []
		SIM_DATA m_sdTCA37;           //NS_VAR [TCA37] [User] []
		SIM_DATA m_sdTCA38;           //NS_VAR [TCA38] [User] []
		SIM_DATA m_sdTCA39;           //NS_VAR [TCA39] [User] []
		SIM_DATA m_sdTCA310;           //NS_VAR [TCA310] [User] []
		SIM_DATA m_sdTCAL3;           //NS_VAR [TCAL3] [User] []
		SIM_DATA m_sdTLA31;           //NS_VAR [TLA31] [User] []
		SIM_DATA m_sdTLA32;           //NS_VAR [TLA32] [User] []
		SIM_DATA m_sdTLA33;           //NS_VAR [TLA33] [User] []
		SIM_DATA m_sdTLA34;           //NS_VAR [TLA34] [User] []
		SIM_DATA m_sdTLA35;           //NS_VAR [TLA35] [User] []
		SIM_DATA m_sdTLA36;           //NS_VAR [TLA36] [User] []
		SIM_DATA m_sdTLA37;           //NS_VAR [TLA37] [User] []
		SIM_DATA m_sdTLA38;           //NS_VAR [TLA38] [User] []
		SIM_DATA m_sdTLA39;           //NS_VAR [TLA39] [User] []
		SIM_DATA m_sdTLA310;           //NS_VAR [TLA310] [User] []
		SIM_DATA m_sdTLAL3;           //NS_VAR [TLAL3] [User] []
		SIM_DATA m_sdTKW3;           //NS_VAR [TKW3] [User] []
		SIM_DATA m_sdTKF03;           //NS_VAR [TKF03] [User] []
		SIM_DATA m_sdTKF3;           //NS_VAR [TKF3] [User] []
		SIM_DATA m_sdTHDIFF3;           //NS_VAR [THDIFF3] [User] []
		SIM_DATA m_sdbta3;           //NS_VAR [bta3] [User] []
		SIM_DATA m_sddynvis3;           //NS_VAR [dynvis3] [User] []
		SIM_DATA m_sdALF1;           //NS_VAR [ALF1] [User] []
		SIM_DATA m_sdALF2;           //NS_VAR [ALF2] [User] []
		SIM_DATA m_sdALF3;           //NS_VAR [ALF3] [User] []
		SIM_DATA m_sdALF4;           //NS_VAR [ALF4] [User] []
		SIM_DATA m_sdALF5;           //NS_VAR [ALF5] [User] []
		SIM_DATA m_sdALF6;           //NS_VAR [ALF6] [User] []
		SIM_DATA m_sdALF7;           //NS_VAR [ALF7] [User] []
		SIM_DATA m_sdALF8;           //NS_VAR [ALF8] [User] []
		SIM_DATA m_sdALF9;           //NS_VAR [ALF9] [User] []
		SIM_DATA m_sdALF10;           //NS_VAR [ALF10] [User] []
		SIM_DATA m_sdRFBA1;           //NS_VAR [RFBA1] [User] []
		SIM_DATA m_sdRFBA2;           //NS_VAR [RFBA2] [User] []
		SIM_DATA m_sdRFBA3;           //NS_VAR [RFBA3] [User] []
		SIM_DATA m_sdRFBA;           //NS_VAR [RFBA] [User] []
		SIM_DATA m_sdVF1;           //NS_VAR [Region 1 Void Fraction] [Radiolytic Gas Profile] []
		SIM_DATA m_sdVF2;           //NS_VAR [Region 2 Void Fraction] [Radiolytic Gas Profile] []
		SIM_DATA m_sdVF3;           //NS_VAR [Region 3 Void Fraction] [Radiolytic Gas Profile] []
		SIM_DATA m_sdVF4;           //NS_VAR [Region 4 Void Fraction] [Radiolytic Gas Profile] []
		SIM_DATA m_sdVF5;           //NS_VAR [Region 5 Void Fraction] [Radiolytic Gas Profile] []
		SIM_DATA m_sdVF6;           //NS_VAR [Region 6 Void Fraction] [Radiolytic Gas Profile] []
		SIM_DATA m_sdVF7;           //NS_VAR [Region 7 Void Fraction] [Radiolytic Gas Profile] []
		SIM_DATA m_sdVF8;           //NS_VAR [Region 8 Void Fraction] [Radiolytic Gas Profile] []
		SIM_DATA m_sdVF9;           //NS_VAR [Region 9 Void Fraction] [Radiolytic Gas Profile] []
		SIM_DATA m_sdVF10;           //NS_VAR [Region 10 Void Fraction] [Radiolytic Gas Profile] []
		SIM_DATA m_sdRFBV1;           //NS_VAR [RFBV1] [User] []
		SIM_DATA m_sdRFBV2;           //NS_VAR [RFBV2] [User] []
		SIM_DATA m_sdRFBV3;           //NS_VAR [RFBV3] [User] []
		SIM_DATA m_sdRFBV;           //NS_VAR [RFBV] [User] []
		SIM_DATA m_sdR;           //NS_VAR [System Reactivity] [Performance] [$]
		SIM_DATA m_sdENP;           //NS_VAR [ENP] [User] []
		SIM_DATA m_sdSUM;           //NS_VAR [SUM] [User] []
		SIM_DATA m_sdQS;           //NS_VAR [QS] [User] []
		SIM_DATA m_sdENDOT;           //NS_VAR [ENDOT] [User] []
		SIM_DATA m_sdENLOG;           //NS_VAR [ENLOG] [User] []
		SIM_DATA m_sdmXS;           //NS_VAR [mXS] [User] []
		SIM_DATA m_sdVav;           //NS_VAR [Vav] [User] []
		SIM_DATA m_sdSav;           //NS_VAR [Sav] [User] []
		SIM_DATA m_sdFND;           //NS_VAR [FND] [User] []
		SIM_DATA m_sdPCF;           //NS_VAR [PCF] [User] []
		SIM_DATA m_sdkw;           //NS_VAR [Power] [Performance] [kW]
		SIM_DATA m_sdWF1;           //NS_VAR [WF1] [User] []
		SIM_DATA m_sdWF2;           //NS_VAR [WF2] [User] []
		SIM_DATA m_sdWF3;           //NS_VAR [WF3] [User] []
		SIM_DATA m_sdWFF1;           //NS_VAR [WFF1] [User] []
		SIM_DATA m_sdWFF2;           //NS_VAR [WFF2] [User] []
		SIM_DATA m_sdWFF3;           //NS_VAR [WFF3] [User] []
		SIM_DATA m_sdWC;           //NS_VAR [Coolant Flow in Loop 1] [Thermal Parameters] [kg/s] stability
		SIM_DATA m_sdWC2;           //NS_VAR [Coolant Flow in Loop 2] [Thermal Parameters] [kg/s] stability
		SIM_DATA m_sdWC3;           //NS_VAR [Coolant Flow in Loop 3] [Thermal Parameters] [kg/s] stability
		SIM_DATA m_sdVF;           //NS_VAR [Core Averaged Void Fraction] [Performance] []
		SIM_DATA m_sdTWA1;           //NS_VAR [TWA1] [User] []
		SIM_DATA m_sdTHOT1;           //NS_VAR [THOT1] [User] []
		SIM_DATA m_sdTCOLD1;           //NS_VAR [TCOLD1] [User] []
		SIM_DATA m_sdFLDT;           //NS_VAR [FLDT] [User] []
		SIM_DATA m_sdDT1;           //NS_VAR [DT1] [User] []
		SIM_DATA m_sdLPr1;           //NS_VAR [Loop 1 Prandtl Number] [Thermal Parameters] []
		SIM_DATA m_sdLRa1;           //NS_VAR [Loop 1 Rayleigh Number] [Thermal Parameters] []
		SIM_DATA m_sdLNu1;           //NS_VAR [Loop 1 Nusselt Number] [Thermal Parameters] []
		SIM_DATA m_sdHTNC1;           //NS_VAR [Loop 1 Natural Convection Heat Transfer Coefficient] [Thermal Parameters] [KJ/hr-m^2-K]
		SIM_DATA m_sdLRe1;           //NS_VAR [Loop 1 Reynolds Number] [Thermal Parameters] []
		SIM_DATA m_sdLe1;           //NS_VAR [Le1] [User] []
		SIM_DATA m_sdLf1;           //NS_VAR [Lf1] [User] []
		SIM_DATA m_sdLNuFf1;           //NS_VAR [LNuFf1] [User] []
		SIM_DATA m_sdLNuFf2;           //NS_VAR [LNuFf2] [User] []
		SIM_DATA m_sdLNuF1;           //NS_VAR [Loop 1 Nusselt Number for Forced Convection] [Thermal Parameters] []
		SIM_DATA m_sdHT1;           //NS_VAR [Loop 1 Forced Convection Heat Transfer Coefficient] [Thermal Parameters] [KJ/hr-m^2-K]
		SIM_DATA m_sdGMMA;           //NS_VAR [GMMA] [User] []
		SIM_DATA m_sdGAMMA;           //NS_VAR [GAMMA] [User] []
		SIM_DATA m_sdGAMMA9;           //NS_VAR [GAMMA9] [User] []
		SIM_DATA m_sdST1;           //NS_VAR [ST1] [User] []
		SIM_DATA m_sdTEM1DOT;           //NS_VAR [TEM1DOT] [User] []
		SIM_DATA m_sdVFT1;           //NS_VAR [VFT1] [User] []
		SIM_DATA m_sdRF1;           //NS_VAR [RF1] [User] []
		SIM_DATA m_sdTL11DOT;           //NS_VAR [TL11DOT] [User] []
		SIM_DATA m_sdVLT11;           //NS_VAR [VLT11] [User] []
		SIM_DATA m_sdRL11;           //NS_VAR [RL11] [User] []
		SIM_DATA m_sdTL12DOT;           //NS_VAR [TL12DOT] [User] []
		SIM_DATA m_sdVLT12;           //NS_VAR [VLT12] [User] []
		SIM_DATA m_sdRL12;           //NS_VAR [RL12] [User] []
		SIM_DATA m_sdTL21DOT;           //NS_VAR [TL21DOT] [User] []
		SIM_DATA m_sdVLT21;           //NS_VAR [VLT21] [User] []
		SIM_DATA m_sdRL21;           //NS_VAR [RL21] [User] []
		SIM_DATA m_sdTL22DOT;           //NS_VAR [TL22DOT] [User] []
		SIM_DATA m_sdVLT22;           //NS_VAR [VLT22] [User] []
		SIM_DATA m_sdRL22;           //NS_VAR [RL22] [User] []
		SIM_DATA m_sdTL31DOT;           //NS_VAR [TL31DOT] [User] []
		SIM_DATA m_sdVLT31;           //NS_VAR [VLT31] [User] []
		SIM_DATA m_sdRL31;           //NS_VAR [RL31] [User] []
		SIM_DATA m_sdTL32DOT;           //NS_VAR [TL32DOT] [User] []
		SIM_DATA m_sdVLT32;           //NS_VAR [VLT32] [User] []
		SIM_DATA m_sdRL32;           //NS_VAR [RL32] [User] []
		SIM_DATA m_sdTL41DOT;           //NS_VAR [TL41DOT] [User] []
		SIM_DATA m_sdVLT41;           //NS_VAR [VLT41] [User] []
		SIM_DATA m_sdRL41;           //NS_VAR [RL41] [User] []
		SIM_DATA m_sdTL42DOT;           //NS_VAR [TL42DOT] [User] []
		SIM_DATA m_sdVLT42;           //NS_VAR [VLT42] [User] []
		SIM_DATA m_sdRL42;           //NS_VAR [RL42] [User] []
		SIM_DATA m_sdTL51DOT;           //NS_VAR [TL51DOT] [User] []
		SIM_DATA m_sdVLT51;           //NS_VAR [VLT51] [User] []
		SIM_DATA m_sdRL51;           //NS_VAR [RL51] [User] []
		SIM_DATA m_sdTL52DOT;           //NS_VAR [TL52DOT] [User] []
		SIM_DATA m_sdVLT52;           //NS_VAR [VLT52] [User] []
		SIM_DATA m_sdRL52;           //NS_VAR [RL52] [User] []
		SIM_DATA m_sdTL61DOT;           //NS_VAR [TL61DOT] [User] []
		SIM_DATA m_sdVLT61;           //NS_VAR [VLT61] [User] []
		SIM_DATA m_sdRL61;           //NS_VAR [RL61] [User] []
		SIM_DATA m_sdTL62DOT;           //NS_VAR [TL62DOT] [User] []
		SIM_DATA m_sdVLT62;           //NS_VAR [VLT62] [User] []
		SIM_DATA m_sdRL62;           //NS_VAR [RL62] [User] []
		SIM_DATA m_sdTL71DOT;           //NS_VAR [TL71DOT] [User] []
		SIM_DATA m_sdVLT71;           //NS_VAR [VLT71] [User] []
		SIM_DATA m_sdRL71;           //NS_VAR [RL71] [User] []
		SIM_DATA m_sdTL72DOT;           //NS_VAR [TL72DOT] [User] []
		SIM_DATA m_sdVLT72;           //NS_VAR [VLT72] [User] []
		SIM_DATA m_sdRL72;           //NS_VAR [RL72] [User] []
		SIM_DATA m_sdTL81DOT;           //NS_VAR [TL81DOT] [User] []
		SIM_DATA m_sdVLT81;           //NS_VAR [VLT81] [User] []
		SIM_DATA m_sdRL81;           //NS_VAR [RL81] [User] []
		SIM_DATA m_sdTL82DOT;           //NS_VAR [TL82DOT] [User] []
		SIM_DATA m_sdVLT82;           //NS_VAR [VLT82] [User] []
		SIM_DATA m_sdRL82;           //NS_VAR [RL82] [User] []
		SIM_DATA m_sdTL91DOT;           //NS_VAR [TL91DOT] [User] []
		SIM_DATA m_sdVLT91;           //NS_VAR [VLT91] [User] []
		SIM_DATA m_sdRL91;           //NS_VAR [RL91] [User] []
		SIM_DATA m_sdTL92DOT;           //NS_VAR [TL92DOT] [User] []
		SIM_DATA m_sdVLT92;           //NS_VAR [VLT92] [User] []
		SIM_DATA m_sdRL92;           //NS_VAR [RL92] [User] []
		SIM_DATA m_sdTL101DOT;           //NS_VAR [TL101DOT] [User] []
		SIM_DATA m_sdVLT101;           //NS_VAR [VLT101] [User] []
		SIM_DATA m_sdRL101;           //NS_VAR [RL101] [User] []
		SIM_DATA m_sdTL102DOT;           //NS_VAR [TL102DOT] [User] []
		SIM_DATA m_sdVLT102;           //NS_VAR [VLT102] [User] []
		SIM_DATA m_sdRL102;           //NS_VAR [RL102] [User] []
		SIM_DATA m_sdST2;           //NS_VAR [ST2] [User] []
		SIM_DATA m_sdTEM2DOT;           //NS_VAR [TEM2DOT] [User] []
		SIM_DATA m_sdVFT2;           //NS_VAR [VFT2] [User] []
		SIM_DATA m_sdRF2;           //NS_VAR [RF2] [User] []
		SIM_DATA m_sdST3;           //NS_VAR [ST3] [User] []
		SIM_DATA m_sdTEM3DOT;           //NS_VAR [TEM3DOT] [User] []
		SIM_DATA m_sdVFT3;           //NS_VAR [VFT3] [User] []
		SIM_DATA m_sdRF3;           //NS_VAR [RF3] [User] []
		SIM_DATA m_sdST4;           //NS_VAR [ST4] [User] []
		SIM_DATA m_sdTEM4DOT;           //NS_VAR [TEM4DOT] [User] []
		SIM_DATA m_sdVFT4;           //NS_VAR [VFT4] [User] []
		SIM_DATA m_sdRF4;           //NS_VAR [RF4] [User] []
		SIM_DATA m_sdST5;           //NS_VAR [ST5] [User] []
		SIM_DATA m_sdTEM5DOT;           //NS_VAR [TEM5DOT] [User] []
		SIM_DATA m_sdVFT5;           //NS_VAR [VFT5] [User] []
		SIM_DATA m_sdRF5;           //NS_VAR [RF5] [User] []
		SIM_DATA m_sdST6;           //NS_VAR [ST6] [User] []
		SIM_DATA m_sdTEM6DOT;           //NS_VAR [TEM6DOT] [User] []
		SIM_DATA m_sdVFT6;           //NS_VAR [VFT6] [User] []
		SIM_DATA m_sdRF6;           //NS_VAR [RF6] [User] []
		SIM_DATA m_sdST7;           //NS_VAR [ST7] [User] []
		SIM_DATA m_sdTEM7DOT;           //NS_VAR [TEM7DOT] [User] []
		SIM_DATA m_sdVFT7;           //NS_VAR [VFT7] [User] []
		SIM_DATA m_sdRF7;           //NS_VAR [RF7] [User] []
		SIM_DATA m_sdST8;           //NS_VAR [ST8] [User] []
		SIM_DATA m_sdTEM8DOT;           //NS_VAR [TEM8DOT] [User] []
		SIM_DATA m_sdVFT8;           //NS_VAR [VFT8] [User] []
		SIM_DATA m_sdRF8;           //NS_VAR [RF8] [User] []
		SIM_DATA m_sdST9;           //NS_VAR [ST9] [User] []
		SIM_DATA m_sdTEM9DOT;           //NS_VAR [TEM9DOT] [User] []
		SIM_DATA m_sdVFT9;           //NS_VAR [VFT9] [User] []
		SIM_DATA m_sdRF9;           //NS_VAR [RF9] [User] []
		SIM_DATA m_sdST10;           //NS_VAR [ST10] [User] []
		SIM_DATA m_sdTEM10DT;           //NS_VAR [TEM10DT] [User] []
		SIM_DATA m_sdVFT10;           //NS_VAR [VFT10] [User] []
		SIM_DATA m_sdRF10;           //NS_VAR [RF10] [User] []
		SIM_DATA m_sdVFUEL;           //NS_VAR [VFUEL] [User] []
		SIM_DATA m_sdVFT;           //NS_VAR [VFT] [User] []
		SIM_DATA m_sdP;           //NS_VAR [P] [User] []
		SIM_DATA m_sdSS10;           //NS_VAR [SS10] [User] []
		SIM_DATA m_sdVS10DOT;           //NS_VAR [VS10DOT] [User] []
		SIM_DATA m_sdSS9;           //NS_VAR [SS9] [User] []
		SIM_DATA m_sdVS9DOT;           //NS_VAR [VS9DOT] [User] []
		SIM_DATA m_sdSS8;           //NS_VAR [SS8] [User] []
		SIM_DATA m_sdVS8DOT;           //NS_VAR [VS8DOT] [User] []
		SIM_DATA m_sdSS7;           //NS_VAR [SS7] [User] []
		SIM_DATA m_sdVS7DOT;           //NS_VAR [VS7DOT] [User] []
		SIM_DATA m_sdSS6;           //NS_VAR [SS6] [User] []
		SIM_DATA m_sdVS6DOT;           //NS_VAR [VS6DOT] [User] []
		SIM_DATA m_sdSS5;           //NS_VAR [SS5] [User] []
		SIM_DATA m_sdVS5DOT;           //NS_VAR [VS5DOT] [User] []
		SIM_DATA m_sdSS4;           //NS_VAR [SS4] [User] []
		SIM_DATA m_sdVS4DOT;           //NS_VAR [VS4DOT] [User] []
		SIM_DATA m_sdSS3;           //NS_VAR [SS3] [User] []
		SIM_DATA m_sdVS3DOT;           //NS_VAR [VS3DOT] [User] []
		SIM_DATA m_sdSS2;           //NS_VAR [SS2] [User] []
		SIM_DATA m_sdVS2DOT;           //NS_VAR [VS2DOT] [User] []
		SIM_DATA m_sdSS1;           //NS_VAR [SS1] [User] []
		SIM_DATA m_sdVS1DOT;           //NS_VAR [VS1DOT] [User] []
		SIM_DATA m_sdMC11;           //NS_VAR [MC11] [User] []
		SIM_DATA m_sdMC12;           //NS_VAR [MC12] [User] []
		SIM_DATA m_sdCPC;           //NS_VAR [CPC] [User] []
		SIM_DATA m_sdFR11;           //NS_VAR [FR11] [User] []
		SIM_DATA m_sdFR12;           //NS_VAR [FR12] [User] []
		SIM_DATA m_sdTAUC11;           //NS_VAR [TAUC11] [User] []
		SIM_DATA m_sdTAUC12;           //NS_VAR [TAUC12] [User] []
		SIM_DATA m_sdMC21;           //NS_VAR [MC21] [User] []
		SIM_DATA m_sdMC22;           //NS_VAR [MC22] [User] []
		SIM_DATA m_sdFR21;           //NS_VAR [FR21] [User] []
		SIM_DATA m_sdFR22;           //NS_VAR [FR22] [User] []
		SIM_DATA m_sdTAUC21;           //NS_VAR [TAUC21] [User] []
		SIM_DATA m_sdTAUC22;           //NS_VAR [TAUC22] [User] []
		SIM_DATA m_sdMC31;           //NS_VAR [MC31] [User] []
		SIM_DATA m_sdMC32;           //NS_VAR [MC32] [User] []
		SIM_DATA m_sdFR31;           //NS_VAR [FR31] [User] []
		SIM_DATA m_sdFR32;           //NS_VAR [FR32] [User] []
		SIM_DATA m_sdTAUC31;           //NS_VAR [TAUC31] [User] []
		SIM_DATA m_sdTAUC32;           //NS_VAR [TAUC32] [User] []
		SIM_DATA m_sdMC41;           //NS_VAR [MC41] [User] []
		SIM_DATA m_sdMC42;           //NS_VAR [MC42] [User] []
		SIM_DATA m_sdFR41;           //NS_VAR [FR41] [User] []
		SIM_DATA m_sdFR42;           //NS_VAR [FR42] [User] []
		SIM_DATA m_sdTAUC41;           //NS_VAR [TAUC41] [User] []
		SIM_DATA m_sdTAUC42;           //NS_VAR [TAUC42] [User] []
		SIM_DATA m_sdMC51;           //NS_VAR [MC51] [User] []
		SIM_DATA m_sdMC52;           //NS_VAR [MC52] [User] []
		SIM_DATA m_sdFR51;           //NS_VAR [FR51] [User] []
		SIM_DATA m_sdFR52;           //NS_VAR [FR52] [User] []
		SIM_DATA m_sdTAUC51;           //NS_VAR [TAUC51] [User] []
		SIM_DATA m_sdTAUC52;           //NS_VAR [TAUC52] [User] []
		SIM_DATA m_sdMC61;           //NS_VAR [MC61] [User] []
		SIM_DATA m_sdMC62;           //NS_VAR [MC62] [User] []
		SIM_DATA m_sdFR61;           //NS_VAR [FR61] [User] []
		SIM_DATA m_sdFR62;           //NS_VAR [FR62] [User] []
		SIM_DATA m_sdTAUC61;           //NS_VAR [TAUC61] [User] []
		SIM_DATA m_sdTAUC62;           //NS_VAR [TAUC62] [User] []
		SIM_DATA m_sdMC71;           //NS_VAR [MC71] [User] []
		SIM_DATA m_sdMC72;           //NS_VAR [MC72] [User] []
		SIM_DATA m_sdFR71;           //NS_VAR [FR71] [User] []
		SIM_DATA m_sdFR72;           //NS_VAR [FR72] [User] []
		SIM_DATA m_sdTAUC71;           //NS_VAR [TAUC71] [User] []
		SIM_DATA m_sdTAUC72;           //NS_VAR [TAUC72] [User] []
		SIM_DATA m_sdMC81;           //NS_VAR [MC81] [User] []
		SIM_DATA m_sdMC82;           //NS_VAR [MC82] [User] []
		SIM_DATA m_sdFR81;           //NS_VAR [FR81] [User] []
		SIM_DATA m_sdFR82;           //NS_VAR [FR82] [User] []
		SIM_DATA m_sdTAUC81;           //NS_VAR [TAUC81] [User] []
		SIM_DATA m_sdTAUC82;           //NS_VAR [TAUC82] [User] []
		SIM_DATA m_sdMC91;           //NS_VAR [MC91] [User] []
		SIM_DATA m_sdMC92;           //NS_VAR [MC92] [User] []
		SIM_DATA m_sdFR91;           //NS_VAR [FR91] [User] []
		SIM_DATA m_sdFR92;           //NS_VAR [FR92] [User] []
		SIM_DATA m_sdTAUC91;           //NS_VAR [TAUC91] [User] []
		SIM_DATA m_sdTAUC92;           //NS_VAR [TAUC92] [User] []
		SIM_DATA m_sdMC101;           //NS_VAR [MC101] [User] []
		SIM_DATA m_sdMC102;           //NS_VAR [MC102] [User] []
		SIM_DATA m_sdFR101;           //NS_VAR [FR101] [User] []
		SIM_DATA m_sdFR102;           //NS_VAR [FR102] [User] []
		SIM_DATA m_sdTAUC101;           //NS_VAR [TAUC101] [User] []
		SIM_DATA m_sdTAUC102;           //NS_VAR [TAUC102] [User] []
		SIM_DATA m_sdMP2;           //NS_VAR [MP2] [User] []
		SIM_DATA m_sdTAUP2;           //NS_VAR [TAUP2] [User] []
		SIM_DATA m_sdMT1;           //NS_VAR [MT1] [User] []
		SIM_DATA m_sdTAUT1;           //NS_VAR [TAUT1] [User] []
		SIM_DATA m_sdGAM1;           //NS_VAR [GAM1] [User] []
		SIM_DATA m_sdMP1;           //NS_VAR [MP1] [User] []
		SIM_DATA m_sdTAUP1;           //NS_VAR [TAUP1] [User] []
		SIM_DATA m_sdWCS2;           //NS_VAR [WCS2] [User] []
		SIM_DATA m_sdMS1;           //NS_VAR [MS1] [User] []
		SIM_DATA m_sdTAUS1;           //NS_VAR [TAUS1] [User] []
		SIM_DATA m_sdGAM2;           //NS_VAR [GAM2] [User] []
		SIM_DATA m_sdGAM3;           //NS_VAR [GAM3] [User] []
		SIM_DATA m_sdMT;           //NS_VAR [MT] [User] []
		SIM_DATA m_sdCPT;           //NS_VAR [CPT] [User] []
		SIM_DATA m_sdMS;           //NS_VAR [MS] [User] []
		SIM_DATA m_sdCPS;           //NS_VAR [CPS] [User] []
		SIM_DATA m_sdHCDOT;           //NS_VAR [HCDOT] [User] []
		SIM_DATA m_sdHTDOT;           //NS_VAR [HTDOT] [User] []
		SIM_DATA m_sdHSDOT;           //NS_VAR [HSDOT] [User] []
		SIM_DATA m_sdHC;           //NS_VAR [HC] [User] []
		SIM_DATA m_sdHC1;           //NS_VAR [HC1] [User] []
		SIM_DATA m_sdHC2;           //NS_VAR [HC2] [User] []
		SIM_DATA m_sdHC3;           //NS_VAR [HC3] [User] []
		SIM_DATA m_sdHC4;           //NS_VAR [HC4] [User] []
		SIM_DATA m_sdHC5;           //NS_VAR [HC5] [User] []
		SIM_DATA m_sdHC6;           //NS_VAR [HC6] [User] []
		SIM_DATA m_sdHC7;           //NS_VAR [HC7] [User] []
		SIM_DATA m_sdHC8;           //NS_VAR [HC8] [User] []
		SIM_DATA m_sdHC9;           //NS_VAR [HC9] [User] []
		SIM_DATA m_sdHC10;           //NS_VAR [HC10] [User] []
		SIM_DATA m_sdHCL;           //NS_VAR [HCL] [User] []
		SIM_DATA m_sdHSHELLS;           //NS_VAR [HSHELLS] [User] []
		SIM_DATA m_sdHTUBES;           //NS_VAR [HTUBES] [User] []
		SIM_DATA m_sdHSHELL;           //NS_VAR [HSHELL] [User] []
		SIM_DATA m_sdHTUBE;           //NS_VAR [HTUBE] [User] []
		SIM_DATA m_sdHP1;           //NS_VAR [HP1] [User] []
		SIM_DATA m_sdHP2;           //NS_VAR [HP2] [User] []
		SIM_DATA m_sdEB;           //NS_VAR [EB] [User] []
		SIM_DATA m_sdTWA2;           //NS_VAR [TWA2] [User] []
		SIM_DATA m_sdTHOT2;           //NS_VAR [THOT2] [User] []
		SIM_DATA m_sdTCOLD2;           //NS_VAR [TCOLD2] [User] []
		SIM_DATA m_sdDT2;           //NS_VAR [DT2] [User] []
		SIM_DATA m_sdLPr2;           //NS_VAR [Loop 2 Prandtl Number] [Thermal Parameters] []
		SIM_DATA m_sdLRa2;           //NS_VAR [Loop 2 Rayleigh Number] [Thermal Parameters] []
		SIM_DATA m_sdLNu2f1;           //NS_VAR [LNu2f1] [User] []
		SIM_DATA m_sdLNu2f2;           //NS_VAR [LNu2f2] [User] []
		SIM_DATA m_sdLNu2;           //NS_VAR [Loop 2 Natural Convection Nusselt Number] [Thermal Parameters] []
		SIM_DATA m_sdHTNC2;           //NS_VAR [Loop 2 Natural Convection Heat Transfer Coefficient] [Thermal Parameters] [KJ/hr-m^2-K]
		SIM_DATA m_sdLRe2;           //NS_VAR [Loop 2 Reynolds Number] [Thermal Parameters] []
		SIM_DATA m_sdLe2;           //NS_VAR [Le2] [User] []
		SIM_DATA m_sdLNuF2f1;           //NS_VAR [LNuF2f1] [User] []
		SIM_DATA m_sdLNuF2f2;           //NS_VAR [LNuF2f2] [User] []
		SIM_DATA m_sdLNuF2;           //NS_VAR [Loop 2 Forced Convection Nusselt Number] [Thermal Parameters] []
		SIM_DATA m_sdHT2;           //NS_VAR [Loop 2 Forced Convection Heat Transfer Coefficient] [Thermal Parameters] [KJ/hr-m^2-K]
		SIM_DATA m_sdGMMA2;           //NS_VAR [GMMA2] [User] []
		SIM_DATA m_sdGAMMA2;           //NS_VAR [GAMMA2] [User] []
		SIM_DATA m_sdGAMMA90;           //NS_VAR [GAMMA90] [User] []
		SIM_DATA m_sdAK3;           //NS_VAR [AK3] [User] []
		SIM_DATA m_sdalpha2;           //NS_VAR [alpha2] [User] []
		SIM_DATA m_sdTL211DOT;           //NS_VAR [TL211DOT] [User] []
		SIM_DATA m_sdVLT211;           //NS_VAR [VLT211] [User] []
		SIM_DATA m_sdRL211;           //NS_VAR [RL211] [User] []
		SIM_DATA m_sdTL212DOT;           //NS_VAR [TL212DOT] [User] []
		SIM_DATA m_sdVLT212;           //NS_VAR [VLT212] [User] []
		SIM_DATA m_sdRL212;           //NS_VAR [RL212] [User] []
		SIM_DATA m_sdTL221DOT;           //NS_VAR [TL221DOT] [User] []
		SIM_DATA m_sdVLT221;           //NS_VAR [VLT221] [User] []
		SIM_DATA m_sdRL221;           //NS_VAR [RL221] [User] []
		SIM_DATA m_sdTL222DOT;           //NS_VAR [TL222DOT] [User] []
		SIM_DATA m_sdVLT222;           //NS_VAR [VLT222] [User] []
		SIM_DATA m_sdRL222;           //NS_VAR [RL222] [User] []
		SIM_DATA m_sdTL231DOT;           //NS_VAR [TL231DOT] [User] []
		SIM_DATA m_sdVLT231;           //NS_VAR [VLT231] [User] []
		SIM_DATA m_sdRL231;           //NS_VAR [RL231] [User] []
		SIM_DATA m_sdTL232DOT;           //NS_VAR [TL232DOT] [User] []
		SIM_DATA m_sdVLT232;           //NS_VAR [VLT232] [User] []
		SIM_DATA m_sdRL232;           //NS_VAR [RL232] [User] []
		SIM_DATA m_sdTL241DOT;           //NS_VAR [TL241DOT] [User] []
		SIM_DATA m_sdVLT241;           //NS_VAR [VLT241] [User] []
		SIM_DATA m_sdRL241;           //NS_VAR [RL241] [User] []
		SIM_DATA m_sdTL242DOT;           //NS_VAR [TL242DOT] [User] []
		SIM_DATA m_sdVLT242;           //NS_VAR [VLT242] [User] []
		SIM_DATA m_sdRL242;           //NS_VAR [RL242] [User] []
		SIM_DATA m_sdTL251DOT;           //NS_VAR [TL251DOT] [User] []
		SIM_DATA m_sdVLT251;           //NS_VAR [VLT251] [User] []
		SIM_DATA m_sdRL251;           //NS_VAR [RL251] [User] []
		SIM_DATA m_sdTL252DOT;           //NS_VAR [TL252DOT] [User] []
		SIM_DATA m_sdVLT252;           //NS_VAR [VLT252] [User] []
		SIM_DATA m_sdRL252;           //NS_VAR [RL252] [User] []
		SIM_DATA m_sdTL261DOT;           //NS_VAR [TL261DOT] [User] []
		SIM_DATA m_sdVLT261;           //NS_VAR [VLT261] [User] []
		SIM_DATA m_sdRL261;           //NS_VAR [RL261] [User] []
		SIM_DATA m_sdTL262DOT;           //NS_VAR [TL262DOT] [User] []
		SIM_DATA m_sdVLT262;           //NS_VAR [VLT262] [User] []
		SIM_DATA m_sdRL262;           //NS_VAR [RL262] [User] []
		SIM_DATA m_sdTL271DOT;           //NS_VAR [TL271DOT] [User] []
		SIM_DATA m_sdVLT271;           //NS_VAR [VLT271] [User] []
		SIM_DATA m_sdRL271;           //NS_VAR [RL271] [User] []
		SIM_DATA m_sdTL272DOT;           //NS_VAR [TL272DOT] [User] []
		SIM_DATA m_sdVLT272;           //NS_VAR [VLT272] [User] []
		SIM_DATA m_sdRL272;           //NS_VAR [RL272] [User] []
		SIM_DATA m_sdTL281DOT;           //NS_VAR [TL281DOT] [User] []
		SIM_DATA m_sdVLT281;           //NS_VAR [VLT281] [User] []
		SIM_DATA m_sdRL281;           //NS_VAR [RL281] [User] []
		SIM_DATA m_sdTL282DOT;           //NS_VAR [TL282DOT] [User] []
		SIM_DATA m_sdVLT282;           //NS_VAR [VLT282] [User] []
		SIM_DATA m_sdRL282;           //NS_VAR [RL282] [User] []
		SIM_DATA m_sdTL291DOT;           //NS_VAR [TL291DOT] [User] []
		SIM_DATA m_sdVLT291;           //NS_VAR [VLT291] [User] []
		SIM_DATA m_sdRL291;           //NS_VAR [RL291] [User] []
		SIM_DATA m_sdTL292DOT;           //NS_VAR [TL292DOT] [User] []
		SIM_DATA m_sdVLT292;           //NS_VAR [VLT292] [User] []
		SIM_DATA m_sdRL292;           //NS_VAR [RL292] [User] []
		SIM_DATA m_sdTL2101DOT;           //NS_VAR [TL2101DOT] [User] []
		SIM_DATA m_sdVLT2101;           //NS_VAR [VLT2101] [User] []
		SIM_DATA m_sdRL2101;           //NS_VAR [RL2101] [User] []
		SIM_DATA m_sdTL2102DOT;           //NS_VAR [TL2102DOT] [User] []
		SIM_DATA m_sdVLT2102;           //NS_VAR [VLT2102] [User] []
		SIM_DATA m_sdRL2102;           //NS_VAR [RL2102] [User] []
		SIM_DATA m_sdTC2IN;           //NS_VAR [TC2IN] [User] []
		SIM_DATA m_sdCPC2;           //NS_VAR [CPC2] [User] []
		SIM_DATA m_sdMC211;           //NS_VAR [MC211] [User] []
		SIM_DATA m_sdMC212;           //NS_VAR [MC212] [User] []
		SIM_DATA m_sdFR211;           //NS_VAR [FR211] [User] []
		SIM_DATA m_sdFR212;           //NS_VAR [FR212] [User] []
		SIM_DATA m_sdTAUC211;           //NS_VAR [TAUC211] [User] []
		SIM_DATA m_sdTAUC212;           //NS_VAR [TAUC212] [User] []
		SIM_DATA m_sdMC221;           //NS_VAR [MC221] [User] []
		SIM_DATA m_sdMC222;           //NS_VAR [MC222] [User] []
		SIM_DATA m_sdFR221;           //NS_VAR [FR221] [User] []
		SIM_DATA m_sdFR222;           //NS_VAR [FR222] [User] []
		SIM_DATA m_sdTAUC221;           //NS_VAR [TAUC221] [User] []
		SIM_DATA m_sdTAUC222;           //NS_VAR [TAUC222] [User] []
		SIM_DATA m_sdMC231;           //NS_VAR [MC231] [User] []
		SIM_DATA m_sdMC232;           //NS_VAR [MC232] [User] []
		SIM_DATA m_sdFR231;           //NS_VAR [FR231] [User] []
		SIM_DATA m_sdFR232;           //NS_VAR [FR232] [User] []
		SIM_DATA m_sdTAUC231;           //NS_VAR [TAUC231] [User] []
		SIM_DATA m_sdTAUC232;           //NS_VAR [TAUC232] [User] []
		SIM_DATA m_sdMC241;           //NS_VAR [MC241] [User] []
		SIM_DATA m_sdMC242;           //NS_VAR [MC242] [User] []
		SIM_DATA m_sdFR241;           //NS_VAR [FR241] [User] []
		SIM_DATA m_sdFR242;           //NS_VAR [FR242] [User] []
		SIM_DATA m_sdTAUC241;           //NS_VAR [TAUC241] [User] []
		SIM_DATA m_sdTAUC242;           //NS_VAR [TAUC242] [User] []
		SIM_DATA m_sdMC251;           //NS_VAR [MC251] [User] []
		SIM_DATA m_sdMC252;           //NS_VAR [MC252] [User] []
		SIM_DATA m_sdFR251;           //NS_VAR [FR251] [User] []
		SIM_DATA m_sdFR252;           //NS_VAR [FR252] [User] []
		SIM_DATA m_sdTAUC251;           //NS_VAR [TAUC251] [User] []
		SIM_DATA m_sdTAUC252;           //NS_VAR [TAUC252] [User] []
		SIM_DATA m_sdMC261;           //NS_VAR [MC261] [User] []
		SIM_DATA m_sdMC262;           //NS_VAR [MC262] [User] []
		SIM_DATA m_sdFR261;           //NS_VAR [FR261] [User] []
		SIM_DATA m_sdFR262;           //NS_VAR [FR262] [User] []
		SIM_DATA m_sdTAUC261;           //NS_VAR [TAUC261] [User] []
		SIM_DATA m_sdTAUC262;           //NS_VAR [TAUC262] [User] []
		SIM_DATA m_sdMC271;           //NS_VAR [MC271] [User] []
		SIM_DATA m_sdMC272;           //NS_VAR [MC272] [User] []
		SIM_DATA m_sdFR271;           //NS_VAR [FR271] [User] []
		SIM_DATA m_sdFR272;           //NS_VAR [FR272] [User] []
		SIM_DATA m_sdTAUC271;           //NS_VAR [TAUC271] [User] []
		SIM_DATA m_sdTAUC272;           //NS_VAR [TAUC272] [User] []
		SIM_DATA m_sdMC281;           //NS_VAR [MC281] [User] []
		SIM_DATA m_sdMC282;           //NS_VAR [MC282] [User] []
		SIM_DATA m_sdFR281;           //NS_VAR [FR281] [User] []
		SIM_DATA m_sdFR282;           //NS_VAR [FR282] [User] []
		SIM_DATA m_sdTAUC281;           //NS_VAR [TAUC281] [User] []
		SIM_DATA m_sdTAUC282;           //NS_VAR [TAUC282] [User] []
		SIM_DATA m_sdMC291;           //NS_VAR [MC291] [User] []
		SIM_DATA m_sdMC292;           //NS_VAR [MC292] [User] []
		SIM_DATA m_sdFR291;           //NS_VAR [FR291] [User] []
		SIM_DATA m_sdFR292;           //NS_VAR [FR292] [User] []
		SIM_DATA m_sdTAUC291;           //NS_VAR [TAUC291] [User] []
		SIM_DATA m_sdTAUC292;           //NS_VAR [TAUC292] [User] []
		SIM_DATA m_sdMC2101;           //NS_VAR [MC2101] [User] []
		SIM_DATA m_sdMC2102;           //NS_VAR [MC2102] [User] []
		SIM_DATA m_sdFR2101;           //NS_VAR [FR2101] [User] []
		SIM_DATA m_sdFR2102;           //NS_VAR [FR2102] [User] []
		SIM_DATA m_sdTAUC2101;           //NS_VAR [TAUC2101] [User] []
		SIM_DATA m_sdTAUC2102;           //NS_VAR [TAUC2102] [User] []
		SIM_DATA m_sdTWA3;           //NS_VAR [TWA3] [User] []
		SIM_DATA m_sdTHOT3;           //NS_VAR [THOT3] [User] []
		SIM_DATA m_sdTCOLD3;           //NS_VAR [TCOLD3] [User] []
		SIM_DATA m_sdDT3;           //NS_VAR [DT3] [User] []
		SIM_DATA m_sdLPr3;           //NS_VAR [Loop 3 Prandtl Number] [Thermal Parameters] []
		SIM_DATA m_sdLRa3;           //NS_VAR [Loop 3 Rayleigh Number] [Thermal Parameters] []
		SIM_DATA m_sdLNu3;           //NS_VAR [Loop 3 Natural Convection Nusselt Number] [Thermal Parameters] []
		SIM_DATA m_sdHTNC3;           //NS_VAR [Loop 3 Natural Convection Heat Transfer Coefficient] [Thermal Parameters] [KJ/hr-m^2-K]
		SIM_DATA m_sdLRe3;           //NS_VAR [Loop 3 Reynolds Number] [Thermal Parameters] []
		SIM_DATA m_sdLe3;           //NS_VAR [Le3] [User] []
		SIM_DATA m_sdLf3;           //NS_VAR [Lf3] [User] []
		SIM_DATA m_sdLNuF3f1;           //NS_VAR [LNuF3f1] [User] []
		SIM_DATA m_sdLNuF3f2;           //NS_VAR [LNuF3f2] [User] []
		SIM_DATA m_sdLNuF3;           //NS_VAR [Loop 3 Forced Convection Nusselt Number] [Thermal Parameters] []
		SIM_DATA m_sdHT3;           //NS_VAR [Loop 3 Forced Convection Heat Transfer Coefficient] [Thermal Parameters] [KJ/hr-m^2-K]
		SIM_DATA m_sdGMMA3;           //NS_VAR [GMMA3] [User] []
		SIM_DATA m_sdGAMMA3;           //NS_VAR [GAMMA3] [User] []
		SIM_DATA m_sdGAMMA95;           //NS_VAR [GAMMA95] [User] []
		SIM_DATA m_sdAK4;           //NS_VAR [AK4] [User] []
		SIM_DATA m_sdalpha3;           //NS_VAR [alpha3] [User] []
		SIM_DATA m_sdTL311DOT;           //NS_VAR [TL311DOT] [User] []
		SIM_DATA m_sdVLT311;           //NS_VAR [VLT311] [User] []
		SIM_DATA m_sdRL311;           //NS_VAR [RL311] [User] []
		SIM_DATA m_sdTL312DOT;           //NS_VAR [TL312DOT] [User] []
		SIM_DATA m_sdVLT312;           //NS_VAR [VLT312] [User] []
		SIM_DATA m_sdRL312;           //NS_VAR [RL312] [User] []
		SIM_DATA m_sdTL321DOT;           //NS_VAR [TL321DOT] [User] []
		SIM_DATA m_sdVLT321;           //NS_VAR [VLT321] [User] []
		SIM_DATA m_sdRL321;           //NS_VAR [RL321] [User] []
		SIM_DATA m_sdTL322DOT;           //NS_VAR [TL322DOT] [User] []
		SIM_DATA m_sdVLT322;           //NS_VAR [VLT322] [User] []
		SIM_DATA m_sdRL322;           //NS_VAR [RL322] [User] []
		SIM_DATA m_sdTL331DOT;           //NS_VAR [TL331DOT] [User] []
		SIM_DATA m_sdVLT331;           //NS_VAR [VLT331] [User] []
		SIM_DATA m_sdRL331;           //NS_VAR [RL331] [User] []
		SIM_DATA m_sdTL332DOT;           //NS_VAR [TL332DOT] [User] []
		SIM_DATA m_sdVLT332;           //NS_VAR [VLT332] [User] []
		SIM_DATA m_sdRL332;           //NS_VAR [RL332] [User] []
		SIM_DATA m_sdTL341DOT;           //NS_VAR [TL341DOT] [User] []
		SIM_DATA m_sdVLT341;           //NS_VAR [VLT341] [User] []
		SIM_DATA m_sdRL341;           //NS_VAR [RL341] [User] []
		SIM_DATA m_sdTL342DOT;           //NS_VAR [TL342DOT] [User] []
		SIM_DATA m_sdVLT342;           //NS_VAR [VLT342] [User] []
		SIM_DATA m_sdRL342;           //NS_VAR [RL342] [User] []
		SIM_DATA m_sdTL351DOT;           //NS_VAR [TL351DOT] [User] []
		SIM_DATA m_sdVLT351;           //NS_VAR [VLT351] [User] []
		SIM_DATA m_sdRL351;           //NS_VAR [RL351] [User] []
		SIM_DATA m_sdTL352DOT;           //NS_VAR [TL352DOT] [User] []
		SIM_DATA m_sdVLT352;           //NS_VAR [VLT352] [User] []
		SIM_DATA m_sdRL352;           //NS_VAR [RL352] [User] []
		SIM_DATA m_sdTL361DOT;           //NS_VAR [TL361DOT] [User] []
		SIM_DATA m_sdVLT361;           //NS_VAR [VLT361] [User] []
		SIM_DATA m_sdRL361;           //NS_VAR [RL361] [User] []
		SIM_DATA m_sdTL362DOT;           //NS_VAR [TL362DOT] [User] []
		SIM_DATA m_sdVLT362;           //NS_VAR [VLT362] [User] []
		SIM_DATA m_sdRL362;           //NS_VAR [RL362] [User] []
		SIM_DATA m_sdTL371DOT;           //NS_VAR [TL371DOT] [User] []
		SIM_DATA m_sdVLT371;           //NS_VAR [VLT371] [User] []
		SIM_DATA m_sdRL371;           //NS_VAR [RL371] [User] []
		SIM_DATA m_sdTL372DOT;           //NS_VAR [TL372DOT] [User] []
		SIM_DATA m_sdVLT372;           //NS_VAR [VLT372] [User] []
		SIM_DATA m_sdRL372;           //NS_VAR [RL372] [User] []
		SIM_DATA m_sdTL381DOT;           //NS_VAR [TL381DOT] [User] []
		SIM_DATA m_sdVLT381;           //NS_VAR [VLT381] [User] []
		SIM_DATA m_sdRL381;           //NS_VAR [RL381] [User] []
		SIM_DATA m_sdTL382DOT;           //NS_VAR [TL382DOT] [User] []
		SIM_DATA m_sdVLT382;           //NS_VAR [VLT382] [User] []
		SIM_DATA m_sdRL382;           //NS_VAR [RL382] [User] []
		SIM_DATA m_sdTL391DOT;           //NS_VAR [TL391DOT] [User] []
		SIM_DATA m_sdVLT391;           //NS_VAR [VLT391] [User] []
		SIM_DATA m_sdRL391;           //NS_VAR [RL391] [User] []
		SIM_DATA m_sdTL392DOT;           //NS_VAR [TL392DOT] [User] []
		SIM_DATA m_sdVLT392;           //NS_VAR [VLT392] [User] []
		SIM_DATA m_sdRL392;           //NS_VAR [RL392] [User] []
		SIM_DATA m_sdTL3101DOT;           //NS_VAR [TL3101DOT] [User] []
		SIM_DATA m_sdVLT3101;           //NS_VAR [VLT3101] [User] []
		SIM_DATA m_sdRL3101;           //NS_VAR [RL3101] [User] []
		SIM_DATA m_sdTL3102DOT;           //NS_VAR [TL3102DOT] [User] []
		SIM_DATA m_sdVLT3102;           //NS_VAR [VLT3102] [User] []
		SIM_DATA m_sdRL3102;           //NS_VAR [RL3102] [User] []
		SIM_DATA m_sdTC3IN;           //NS_VAR [TC3IN] [User] []
		SIM_DATA m_sdCPC3;           //NS_VAR [CPC3] [User] []
		SIM_DATA m_sdMC311;           //NS_VAR [MC311] [User] []
		SIM_DATA m_sdMC312;           //NS_VAR [MC312] [User] []
		SIM_DATA m_sdFR311;           //NS_VAR [FR311] [User] []
		SIM_DATA m_sdFR312;           //NS_VAR [FR312] [User] []
		SIM_DATA m_sdTAUC311;           //NS_VAR [TAUC311] [User] []
		SIM_DATA m_sdTAUC312;           //NS_VAR [TAUC312] [User] []
		SIM_DATA m_sdMC321;           //NS_VAR [MC321] [User] []
		SIM_DATA m_sdMC322;           //NS_VAR [MC322] [User] []
		SIM_DATA m_sdFR321;           //NS_VAR [FR321] [User] []
		SIM_DATA m_sdFR322;           //NS_VAR [FR322] [User] []
		SIM_DATA m_sdTAUC321;           //NS_VAR [TAUC321] [User] []
		SIM_DATA m_sdTAUC322;           //NS_VAR [TAUC322] [User] []
		SIM_DATA m_sdMC331;           //NS_VAR [MC331] [User] []
		SIM_DATA m_sdMC332;           //NS_VAR [MC332] [User] []
		SIM_DATA m_sdFR331;           //NS_VAR [FR331] [User] []
		SIM_DATA m_sdFR332;           //NS_VAR [FR332] [User] []
		SIM_DATA m_sdTAUC331;           //NS_VAR [TAUC331] [User] []
		SIM_DATA m_sdTAUC332;           //NS_VAR [TAUC332] [User] []
		SIM_DATA m_sdMC341;           //NS_VAR [MC341] [User] []
		SIM_DATA m_sdMC342;           //NS_VAR [MC342] [User] []
		SIM_DATA m_sdFR341;           //NS_VAR [FR341] [User] []
		SIM_DATA m_sdFR342;           //NS_VAR [FR342] [User] []
		SIM_DATA m_sdTAUC341;           //NS_VAR [TAUC341] [User] []
		SIM_DATA m_sdTAUC342;           //NS_VAR [TAUC342] [User] []
		SIM_DATA m_sdMC351;           //NS_VAR [MC351] [User] []
		SIM_DATA m_sdMC352;           //NS_VAR [MC352] [User] []
		SIM_DATA m_sdFR351;           //NS_VAR [FR351] [User] []
		SIM_DATA m_sdFR352;           //NS_VAR [FR352] [User] []
		SIM_DATA m_sdTAUC351;           //NS_VAR [TAUC351] [User] []
		SIM_DATA m_sdTAUC352;           //NS_VAR [TAUC352] [User] []
		SIM_DATA m_sdMC361;           //NS_VAR [MC361] [User] []
		SIM_DATA m_sdMC362;           //NS_VAR [MC362] [User] []
		SIM_DATA m_sdFR361;           //NS_VAR [FR361] [User] []
		SIM_DATA m_sdFR362;           //NS_VAR [FR362] [User] []
		SIM_DATA m_sdTAUC361;           //NS_VAR [TAUC361] [User] []
		SIM_DATA m_sdTAUC362;           //NS_VAR [TAUC362] [User] []
		SIM_DATA m_sdMC371;           //NS_VAR [MC371] [User] []
		SIM_DATA m_sdMC372;           //NS_VAR [MC372] [User] []
		SIM_DATA m_sdFR371;           //NS_VAR [FR371] [User] []
		SIM_DATA m_sdFR372;           //NS_VAR [FR372] [User] []
		SIM_DATA m_sdTAUC371;           //NS_VAR [TAUC371] [User] []
		SIM_DATA m_sdTAUC372;           //NS_VAR [TAUC372] [User] []
		SIM_DATA m_sdMC381;           //NS_VAR [MC381] [User] []
		SIM_DATA m_sdMC382;           //NS_VAR [MC382] [User] []
		SIM_DATA m_sdFR381;           //NS_VAR [FR381] [User] []
		SIM_DATA m_sdFR382;           //NS_VAR [FR382] [User] []
		SIM_DATA m_sdTAUC381;           //NS_VAR [TAUC381] [User] []
		SIM_DATA m_sdTAUC382;           //NS_VAR [TAUC382] [User] []
		SIM_DATA m_sdMC391;           //NS_VAR [MC391] [User] []
		SIM_DATA m_sdMC392;           //NS_VAR [MC392] [User] []
		SIM_DATA m_sdFR391;           //NS_VAR [FR391] [User] []
		SIM_DATA m_sdFR392;           //NS_VAR [FR392] [User] []
		SIM_DATA m_sdTAUC391;           //NS_VAR [TAUC391] [User] []
		SIM_DATA m_sdTAUC392;           //NS_VAR [TAUC392] [User] []
		SIM_DATA m_sdMC3101;           //NS_VAR [MC3101] [User] []
		SIM_DATA m_sdMC3102;           //NS_VAR [MC3102] [User] []
		SIM_DATA m_sdFR3101;           //NS_VAR [FR3101] [User] []
		SIM_DATA m_sdFR3102;           //NS_VAR [FR3102] [User] []
		SIM_DATA m_sdTAUC3101;           //NS_VAR [TAUC3101] [User] []
		SIM_DATA m_sdTAUC3102;           //NS_VAR [TAUC3102] [User] []
		SIM_DATA m_sdSUML1;           //NS_VAR [SUML1] [User] []
		SIM_DATA m_sdSUML2;           //NS_VAR [SUML2] [User] []
		SIM_DATA m_sdSUML21;           //NS_VAR [SUML21] [User] []
		SIM_DATA m_sdSUML22;           //NS_VAR [SUML22] [User] []
		SIM_DATA m_sdSUML31;           //NS_VAR [SUML31] [User] []
		SIM_DATA m_sdSUML32;           //NS_VAR [SUML32] [User] []
		SIM_DATA m_sdSML1;           //NS_VAR [SML1] [User] []
		SIM_DATA m_sdSML2;           //NS_VAR [SML2] [User] []
		SIM_DATA m_sdSML3;           //NS_VAR [SML3] [User] []
		SIM_DATA m_sdSUMF;           //NS_VAR [SUMF] [User] []
		SIM_DATA m_sdFRIC;           //NS_VAR [FRIC] [User] []
		SIM_DATA m_sdDISP;           //NS_VAR [DISP] [User] []
		SIM_DATA m_sdT1AV;           //NS_VAR [T1AV] [User] []
		SIM_DATA m_sdPBF;           //NS_VAR [PBF] [User] []
		SIM_DATA m_sdPBL1;           //NS_VAR [PBL1] [User] []
		SIM_DATA m_sdPBL2;           //NS_VAR [PBL2] [User] []
		SIM_DATA m_sdPBL3;           //NS_VAR [PBL3] [User] []
		SIM_DATA m_sdPBLT;           //NS_VAR [PBLT] [User] []
		SIM_DATA m_sdPCL1;           //NS_VAR [PCL1] [User] []
		SIM_DATA m_sdPCL2;           //NS_VAR [PCL2] [User] []
		SIM_DATA m_sdPCL3;           //NS_VAR [PCL3] [User] []
		SIM_DATA m_sdPCLT;           //NS_VAR [PCLT] [User] []
		SIM_DATA m_sdROH2A;           //NS_VAR [ROH2A] [User] []
		SIM_DATA m_sdROO2A;           //NS_VAR [ROO2A] [User] []
		SIM_DATA m_sdROH21;           //NS_VAR [ROH21] [User] []
		SIM_DATA m_sdROO21;           //NS_VAR [ROO21] [User] []
		SIM_DATA m_sdGB;           //NS_VAR [GB] [User] []
		SIM_DATA m_sdGH2;           //NS_VAR [GH2] [User] []
		SIM_DATA m_sdGO2;           //NS_VAR [GO2] [User] []
		SIM_DATA m_sdXH210;           //NS_VAR [XH210] [User] []
		SIM_DATA m_sdXO210;           //NS_VAR [XO210] [User] []
		SIM_DATA m_sdXH21;           //NS_VAR [XH21] [User] []
		SIM_DATA m_sdXO21;           //NS_VAR [XO21] [User] []
		SIM_DATA m_sdED1;           //NS_VAR [ED1] [User] []
		SIM_DATA m_sdXTO;           //NS_VAR [XTO] [User] []
		SIM_DATA m_sdG1H;           //NS_VAR [G1H] [User] []
		SIM_DATA m_sdVH1DOT;           //NS_VAR [VH1DOT] [User] []
		SIM_DATA m_sdG1O;           //NS_VAR [G1O] [User] []
		SIM_DATA m_sdVO1DOT;           //NS_VAR [VO1DOT] [User] []
		SIM_DATA m_sdROH22;           //NS_VAR [ROH22] [User] []
		SIM_DATA m_sdROO22;           //NS_VAR [ROO22] [User] []
		SIM_DATA m_sdXH22;           //NS_VAR [XH22] [User] []
		SIM_DATA m_sdXO22;           //NS_VAR [XO22] [User] []
		SIM_DATA m_sdED2;           //NS_VAR [ED2] [User] []
		SIM_DATA m_sdG2H;           //NS_VAR [G2H] [User] []
		SIM_DATA m_sdVH2DOT;           //NS_VAR [VH2DOT] [User] []
		SIM_DATA m_sdG2O;           //NS_VAR [G2O] [User] []
		SIM_DATA m_sdVO2DOT;           //NS_VAR [VO2DOT] [User] []
		SIM_DATA m_sdROH23;           //NS_VAR [ROH23] [User] []
		SIM_DATA m_sdROO23;           //NS_VAR [ROO23] [User] []
		SIM_DATA m_sdXH23;           //NS_VAR [XH23] [User] []
		SIM_DATA m_sdXO23;           //NS_VAR [XO23] [User] []
		SIM_DATA m_sdED3;           //NS_VAR [ED3] [User] []
		SIM_DATA m_sdG3H;           //NS_VAR [G3H] [User] []
		SIM_DATA m_sdVH3DOT;           //NS_VAR [VH3DOT] [User] []
		SIM_DATA m_sdG3O;           //NS_VAR [G3O] [User] []
		SIM_DATA m_sdVO3DOT;           //NS_VAR [VO3DOT] [User] []
		SIM_DATA m_sdROH24;           //NS_VAR [ROH24] [User] []
		SIM_DATA m_sdROO24;           //NS_VAR [ROO24] [User] []
		SIM_DATA m_sdXH24;           //NS_VAR [XH24] [User] []
		SIM_DATA m_sdXO24;           //NS_VAR [XO24] [User] []
		SIM_DATA m_sdED4;           //NS_VAR [ED4] [User] []
		SIM_DATA m_sdG4H;           //NS_VAR [G4H] [User] []
		SIM_DATA m_sdVH4DOT;           //NS_VAR [VH4DOT] [User] []
		SIM_DATA m_sdG4O;           //NS_VAR [G4O] [User] []
		SIM_DATA m_sdVO4DOT;           //NS_VAR [VO4DOT] [User] []
		SIM_DATA m_sdROH25;           //NS_VAR [ROH25] [User] []
		SIM_DATA m_sdROO25;           //NS_VAR [ROO25] [User] []
		SIM_DATA m_sdXH25;           //NS_VAR [XH25] [User] []
		SIM_DATA m_sdXO25;           //NS_VAR [XO25] [User] []
		SIM_DATA m_sdED5;           //NS_VAR [ED5] [User] []
		SIM_DATA m_sdG5H;           //NS_VAR [G5H] [User] []
		SIM_DATA m_sdVH5DOT;           //NS_VAR [VH5DOT] [User] []
		SIM_DATA m_sdG5O;           //NS_VAR [G5O] [User] []
		SIM_DATA m_sdVO5DOT;           //NS_VAR [VO5DOT] [User] []
		SIM_DATA m_sdROH26;           //NS_VAR [ROH26] [User] []
		SIM_DATA m_sdROO26;           //NS_VAR [ROO26] [User] []
		SIM_DATA m_sdXH26;           //NS_VAR [XH26] [User] []
		SIM_DATA m_sdXO26;           //NS_VAR [XO26] [User] []
		SIM_DATA m_sdED6;           //NS_VAR [ED6] [User] []
		SIM_DATA m_sdG6H;           //NS_VAR [G6H] [User] []
		SIM_DATA m_sdVH6DOT;           //NS_VAR [VH6DOT] [User] []
		SIM_DATA m_sdG6O;           //NS_VAR [G6O] [User] []
		SIM_DATA m_sdVO6DOT;           //NS_VAR [VO6DOT] [User] []
		SIM_DATA m_sdROH27;           //NS_VAR [ROH27] [User] []
		SIM_DATA m_sdROO27;           //NS_VAR [ROO27] [User] []
		SIM_DATA m_sdXH27;           //NS_VAR [XH27] [User] []
		SIM_DATA m_sdXO27;           //NS_VAR [XO27] [User] []
		SIM_DATA m_sdED7;           //NS_VAR [ED7] [User] []
		SIM_DATA m_sdG7H;           //NS_VAR [G7H] [User] []
		SIM_DATA m_sdVH7DOT;           //NS_VAR [VH7DOT] [User] []
		SIM_DATA m_sdG7O;           //NS_VAR [G7O] [User] []
		SIM_DATA m_sdVO7DOT;           //NS_VAR [VO7DOT] [User] []
		SIM_DATA m_sdROH28;           //NS_VAR [ROH28] [User] []
		SIM_DATA m_sdROO28;           //NS_VAR [ROO28] [User] []
		SIM_DATA m_sdXH28;           //NS_VAR [XH28] [User] []
		SIM_DATA m_sdXO28;           //NS_VAR [XO28] [User] []
		SIM_DATA m_sdED8;           //NS_VAR [ED8] [User] []
		SIM_DATA m_sdG8H;           //NS_VAR [G8H] [User] []
		SIM_DATA m_sdVH8DOT;           //NS_VAR [VH8DOT] [User] []
		SIM_DATA m_sdG8O;           //NS_VAR [G8O] [User] []
		SIM_DATA m_sdVO8DOT;           //NS_VAR [VO8DOT] [User] []
		SIM_DATA m_sdROH29;           //NS_VAR [ROH29] [User] []
		SIM_DATA m_sdROO29;           //NS_VAR [ROO29] [User] []
		SIM_DATA m_sdXH29;           //NS_VAR [XH29] [User] []
		SIM_DATA m_sdXO29;           //NS_VAR [XO29] [User] []
		SIM_DATA m_sdED9;           //NS_VAR [ED9] [User] []
		SIM_DATA m_sdG9H;           //NS_VAR [G9H] [User] []
		SIM_DATA m_sdVH9DOT;           //NS_VAR [VH9DOT] [User] []
		SIM_DATA m_sdG9O;           //NS_VAR [G9O] [User] []
		SIM_DATA m_sdVO9DOT;           //NS_VAR [VO9DOT] [User] []
		SIM_DATA m_sdROH210;           //NS_VAR [ROH210] [User] []
		SIM_DATA m_sdROO210;           //NS_VAR [ROO210] [User] []
		SIM_DATA m_sdED10;           //NS_VAR [ED10] [User] []
		SIM_DATA m_sdG10H;           //NS_VAR [G10H] [User] []
		SIM_DATA m_sdVH10DOT;           //NS_VAR [VH10DOT] [User] []
		SIM_DATA m_sdG10O;           //NS_VAR [G10O] [User] []
		SIM_DATA m_sdVO10DOT;           //NS_VAR [VO10DOT] [User] []
		SIM_DATA m_sdHPDOT;           //NS_VAR [HPDOT] [User] []
		SIM_DATA m_sdOPDOT;           //NS_VAR [OPDOT] [User] []
		SIM_DATA m_sdVHTOT;           //NS_VAR [VHTOT] [User] []
		SIM_DATA m_sdVOTOT;           //NS_VAR [VOTOT] [User] []
		SIM_DATA m_sdPTRIP;           //NS_VAR [PTRIP] [User] []
		SIM_DATA m_sdPSIG;           //NS_VAR [PSIG] [User] []
		SIM_DATA m_sdWMUIN;           //NS_VAR [WMUIN] [User] []
		SIM_DATA m_sdWMUDOT;           //NS_VAR [WMUDOT] [User] []
		SIM_DATA m_sdROW;           //NS_VAR [ROW] [User] []
		SIM_DATA m_sdVFDOT;           //NS_VAR [VFDOT] [User] []
		SIM_DATA m_sdVHDT1;           //NS_VAR [VHDT1] [User] []
		SIM_DATA m_sdVHDT2;           //NS_VAR [VHDT2] [User] []
		SIM_DATA m_sdVODT1;           //NS_VAR [VODT1] [User] []
		SIM_DATA m_sdVODT2;           //NS_VAR [VODT2] [User] []
		SIM_DATA m_sdVPDOT;           //NS_VAR [VPDOT] [User] []
		SIM_DATA m_sdVCTOT;           //NS_VAR [VCTOT] [User] []
		SIM_DATA m_sdCPH;           //NS_VAR [CPH] [User] []
		SIM_DATA m_sdCPO;           //NS_VAR [CPO] [User] []
		SIM_DATA m_sdCPN;           //NS_VAR [CPN] [User] []
		SIM_DATA m_sdT20;           //NS_VAR [T20] [User] []
		SIM_DATA m_sdENH20;           //NS_VAR [ENH20] [User] []
		SIM_DATA m_sdENO20;           //NS_VAR [ENO20] [User] []
		SIM_DATA m_sdENN20;           //NS_VAR [ENN20] [User] []
		SIM_DATA m_sdENH1;           //NS_VAR [ENH1] [User] []
		SIM_DATA m_sdENO1;           //NS_VAR [ENO1] [User] []
		SIM_DATA m_sdENO2;           //NS_VAR [ENO2] [User] []
		SIM_DATA m_sdENN2;           //NS_VAR [ENN2] [User] []
		SIM_DATA m_sdENH5;           //NS_VAR [ENH5] [User] []
		SIM_DATA m_sdENO5;           //NS_VAR [ENO5] [User] []
		SIM_DATA m_sdENN5;           //NS_VAR [ENN5] [User] []
		SIM_DATA m_sdRHY;           //NS_VAR [RHY] [User] []
		SIM_DATA m_sdROX;           //NS_VAR [ROX] [User] []
		SIM_DATA m_sdRN;           //NS_VAR [RN] [User] []
		SIM_DATA m_sdHFH;           //NS_VAR [HFH] [User] []
		SIM_DATA m_sdHFO;           //NS_VAR [HFO] [User] []
		SIM_DATA m_sdHFN;           //NS_VAR [HFN] [User] []
		SIM_DATA m_sdHFOUT;           //NS_VAR [HFOUT] [User] []
		SIM_DATA m_sdCVH;           //NS_VAR [CVH] [User] []
		SIM_DATA m_sdCVO;           //NS_VAR [CVO] [User] []
		SIM_DATA m_sdCVN;           //NS_VAR [CVN] [User] []
		SIM_DATA m_sdMCV;           //NS_VAR [MCV] [User] []
		SIM_DATA m_sdTPDOT;           //NS_VAR [TPDOT] [User] []
		SIM_DATA m_sdMHDOT;           //NS_VAR [MHDOT] [User] []
		SIM_DATA m_sdPHDOT;           //NS_VAR [PHDOT] [User] []
		SIM_DATA m_sdH2F;           //NS_VAR [H2F] [User] []
		SIM_DATA m_sdMODOT;           //NS_VAR [MODOT] [User] []
		SIM_DATA m_sdPODOT;           //NS_VAR [PODOT] [User] []
		SIM_DATA m_sdMNDOT;           //NS_VAR [MNDOT] [User] []
		SIM_DATA m_sdPNDOT;           //NS_VAR [PNDOT] [User] []
		SIM_DATA m_sdENPMAX;           //NS_VAR [ENPMAX] [User] []
		SIM_DATA m_sdkwmax;           //NS_VAR [Maximum Power] [Performance] [kW]
		SIM_DATA m_sdRR;           //NS_VAR [RR] [User] []
		SIM_DATA m_sdTEM;           //NS_VAR [TEM] [User] []
		SIM_DATA m_sdTEM2;           //NS_VAR [Coolant Exit Temperature] [Performance] [C]
		SIM_DATA m_sdTEM3;           //NS_VAR [TEM3] [User] []
		SIM_DATA m_sdTEM4;           //NS_VAR [TEM4] [User] []
		SIM_DATA m_sdVOG;           //NS_VAR [VOG] [User] []
		SIM_DATA m_sdPS;           //NS_VAR [PS] [User] []
		SIM_DATA m_sdELOG;           //NS_VAR [ELOG] [User] []
		SIM_DATA m_sdEPOW;           //NS_VAR [EPOW] [User] []
		SIM_DATA m_sdVGAS;           //NS_VAR [VGAS] [User] []
		SIM_DATA m_sdWFG;           //NS_VAR [WFG] [User] []
		SIM_DATA m_sdTEM5;           //NS_VAR [TEM5] [User] []
		SIM_DATA m_sdPDIS;           //NS_VAR [PDIS] [User] []
		SIM_DATA m_sdTLA;           //NS_VAR [TLA] [User] []

		//define state variables here
		SIM_DATA *m_sdEN;           //STATE_VAR [EN] [User] []
		SIM_DATA *m_sdD1;           //STATE_VAR [D1] [User] []
		SIM_DATA *m_sdD2;           //STATE_VAR [D2] [User] []
		SIM_DATA *m_sdD3;           //STATE_VAR [D3] [User] []
		SIM_DATA *m_sdD4;           //STATE_VAR [D4] [User] []
		SIM_DATA *m_sdD5;           //STATE_VAR [D5] [User] []
		SIM_DATA *m_sdD6;           //STATE_VAR [D6] [User] []
		SIM_DATA *m_sdETOT;           //STATE_VAR [ETOT] [User] []
		SIM_DATA *m_sdTEMP1;           //STATE_VAR [Region 1 Fuel Temperature] [Temperature Profile] [C]
		SIM_DATA *m_sdVFUEL1;           //STATE_VAR [VFUEL1] [User] []
		SIM_DATA *m_sdTL11;           //STATE_VAR [TL11] [User] []
		SIM_DATA *m_sdVL11;           //STATE_VAR [VL11] [User] []
		SIM_DATA *m_sdTL12;           //STATE_VAR [Loop 1 Region 1 Boundary Layer Exit Temperature] [Loop 1 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL12;           //STATE_VAR [VL12] [User] []
		SIM_DATA *m_sdTW1;           //STATE_VAR [TW1] [User] []
		SIM_DATA *m_sdTL21;           //STATE_VAR [TL21] [User] []
		SIM_DATA *m_sdVL21;           //STATE_VAR [VL21] [User] []
		SIM_DATA *m_sdTL22;           //STATE_VAR [Loop 1 Region 2 Boundary Layer Exit Temperature] [Loop 1 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL22;           //STATE_VAR [VL22] [User] []
		SIM_DATA *m_sdTW2;           //STATE_VAR [TW2] [User] []
		SIM_DATA *m_sdTL31;           //STATE_VAR [TL31] [User] []
		SIM_DATA *m_sdVL31;           //STATE_VAR [VL31] [User] []
		SIM_DATA *m_sdTL32;           //STATE_VAR [Loop 1 Region 3 Boundary Layer Exit Temperature] [Loop 1 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL32;           //STATE_VAR [VL32] [User] []
		SIM_DATA *m_sdTW3;           //STATE_VAR [TW3] [User] []
		SIM_DATA *m_sdTL41;           //STATE_VAR [TL41] [User] []
		SIM_DATA *m_sdVL41;           //STATE_VAR [VL41] [User] []
		SIM_DATA *m_sdTL42;           //STATE_VAR [Loop 1 Region 4 Boundary Layer Exit Temperature] [Loop 1 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL42;           //STATE_VAR [VL42] [User] []
		SIM_DATA *m_sdTW4;           //STATE_VAR [TW4] [User] []
		SIM_DATA *m_sdTL51;           //STATE_VAR [TL51] [User] []
		SIM_DATA *m_sdVL51;           //STATE_VAR [VL51] [User] []
		SIM_DATA *m_sdTL52;           //STATE_VAR [Loop 1 Region 5 Boundary Layer Exit Temperature] [Loop 1 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL52;           //STATE_VAR [VL52] [User] []
		SIM_DATA *m_sdTW5;           //STATE_VAR [TW5] [User] []
		SIM_DATA *m_sdTL61;           //STATE_VAR [TL61] [User] []
		SIM_DATA *m_sdVL61;           //STATE_VAR [VL61] [User] []
		SIM_DATA *m_sdTL62;           //STATE_VAR [Loop 1 Region 6 Boundary Layer Exit Temperature] [Loop 1 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL62;           //STATE_VAR [VL62] [User] []
		SIM_DATA *m_sdTW6;           //STATE_VAR [TW6] [User] []
		SIM_DATA *m_sdTL71;           //STATE_VAR [TL71] [User] []
		SIM_DATA *m_sdVL71;           //STATE_VAR [VL71] [User] []
		SIM_DATA *m_sdTL72;           //STATE_VAR [Loop 1 Region 7 Boundary Layer Exit Temperature] [Loop 1 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL72;           //STATE_VAR [VL72] [User] []
		SIM_DATA *m_sdTW7;           //STATE_VAR [TW7] [User] []
		SIM_DATA *m_sdTL81;           //STATE_VAR [TL81] [User] []
		SIM_DATA *m_sdVL81;           //STATE_VAR [VL81] [User] []
		SIM_DATA *m_sdTL82;           //STATE_VAR [Loop 1 Region 8 Boundary Layer Exit Temperature] [Loop 1 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL82;           //STATE_VAR [VL82] [User] []
		SIM_DATA *m_sdTW8;           //STATE_VAR [TW8] [User] []
		SIM_DATA *m_sdTL91;           //STATE_VAR [TL91] [User] []
		SIM_DATA *m_sdVL91;           //STATE_VAR [VL91] [User] []
		SIM_DATA *m_sdTL92;           //STATE_VAR [Loop 1 Region 9 Boundary Layer Exit Temperature] [Loop 1 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL92;           //STATE_VAR [VL92] [User] []
		SIM_DATA *m_sdTW9;           //STATE_VAR [TW9] [User] []
		SIM_DATA *m_sdTL101;           //STATE_VAR [TL101] [User] []
		SIM_DATA *m_sdVL101;           //STATE_VAR [VL101] [User] []
		SIM_DATA *m_sdTL102;           //STATE_VAR [Loop 1 Region 10 Boundary Layer Exit Temperature] [Loop 1 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL102;           //STATE_VAR [VL102] [User] []
		SIM_DATA *m_sdTW10;           //STATE_VAR [TW10] [User] []
		SIM_DATA *m_sdTEMP2;           //STATE_VAR [Region 2 Fuel Temperature] [Temperature Profile] [C]
		SIM_DATA *m_sdVFUEL2;           //STATE_VAR [VFUEL2] [User] []
		SIM_DATA *m_sdTEMP3;           //STATE_VAR [Region 3 Fuel Temperature] [Temperature Profile] [C]
		SIM_DATA *m_sdVFUEL3;           //STATE_VAR [VFUEL3] [User] []
		SIM_DATA *m_sdTEMP4;           //STATE_VAR [Region 4 Fuel Temperature] [Temperature Profile] [C]
		SIM_DATA *m_sdVFUEL4;           //STATE_VAR [VFUEL4] [User] []
		SIM_DATA *m_sdTEMP5;           //STATE_VAR [Region 5 Fuel Temperature] [Temperature Profile] [C]
		SIM_DATA *m_sdVFUEL5;           //STATE_VAR [VFUEL5] [User] []
		SIM_DATA *m_sdTEMP6;           //STATE_VAR [Region 6 Fuel Temperature] [Temperature Profile] [C]
		SIM_DATA *m_sdVFUEL6;           //STATE_VAR [VFUEL6] [User] []
		SIM_DATA *m_sdTEMP7;           //STATE_VAR [Region 7 Fuel Temperature] [Temperature Profile] [C]
		SIM_DATA *m_sdVFUEL7;           //STATE_VAR [VFUEL7] [User] []
		SIM_DATA *m_sdTEMP8;           //STATE_VAR [Region 8 Fuel Temperature] [Temperature Profile] [C]
		SIM_DATA *m_sdVFUEL8;           //STATE_VAR [VFUEL8] [User] []
		SIM_DATA *m_sdTEMP9;           //STATE_VAR [Region 9 Fuel Temperature] [Temperature Profile] [C]
		SIM_DATA *m_sdVFUEL9;           //STATE_VAR [VFUEL9] [User] []
		SIM_DATA *m_sdTEMP10;           //STATE_VAR [Region 10 Fuel Temperature] [Temperature Profile] [C]
		SIM_DATA *m_sdVFUEL10;           //STATE_VAR [VFUEL10] [User] []
		SIM_DATA *m_sdVS10;           //STATE_VAR [Region 10 Steam Volume] [Steam Volume] [m3]
		SIM_DATA *m_sdVS9;           //STATE_VAR [Region 9 Steam Volume] [Steam Volume] [m3]
		SIM_DATA *m_sdVS8;           //STATE_VAR [Region 8 Steam Volume] [Steam Volume] [m3]
		SIM_DATA *m_sdVS7;           //STATE_VAR [Region 7 Steam Volume] [Steam Volume] [m3]
		SIM_DATA *m_sdVS6;           //STATE_VAR [Region 6 Steam Volume] [Steam Volume] [m3]
		SIM_DATA *m_sdVS5;           //STATE_VAR [Region 5 Steam Volume] [Steam Volume] [m3]
		SIM_DATA *m_sdVS4;           //STATE_VAR [Region 4 Steam Volume] [Steam Volume] [m3]
		SIM_DATA *m_sdVS3;           //STATE_VAR [Region 3 Steam Volume] [Steam Volume] [m3]
		SIM_DATA *m_sdVS2;           //STATE_VAR [Region 2 Steam Volume] [Steam Volume] [m3]
		SIM_DATA *m_sdVS1;           //STATE_VAR [Region 1 Steam Volume] [Steam Volume] [m3]
		SIM_DATA *m_sdTC11;           //STATE_VAR [TC11] [User] []
		SIM_DATA *m_sdTC12;           //STATE_VAR [Loop1 Region 1 Coolant Exit Temperature] [Loop 1 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC21;           //STATE_VAR [TC21] [User] []
		SIM_DATA *m_sdTC22;           //STATE_VAR [Loop1 Region 2 Coolant Exit Temperature] [Loop 1 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC31;           //STATE_VAR [TC31] [User] []
		SIM_DATA *m_sdTC32;           //STATE_VAR [Loop1 Region 3 Coolant Exit Temperature] [Loop 1 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC41;           //STATE_VAR [TC41] [User] []
		SIM_DATA *m_sdTC42;           //STATE_VAR [Loop1 Region 4 Coolant Exit Temperature] [Loop 1 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC51;           //STATE_VAR [TC51] [User] []
		SIM_DATA *m_sdTC52;           //STATE_VAR [Loop1 Region 5 Coolant Exit Temperature] [Loop 1 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC61;           //STATE_VAR [TC61] [User] []
		SIM_DATA *m_sdTC62;           //STATE_VAR [Loop1 Region 6 Coolant Exit Temperature] [Loop 1 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC71;           //STATE_VAR [TC71] [User] []
		SIM_DATA *m_sdTC72;           //STATE_VAR [Loop1 Region 7 Coolant Exit Temperature] [Loop 1 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC81;           //STATE_VAR [TC81] [User] []
		SIM_DATA *m_sdTC82;           //STATE_VAR [Loop1 Region 8 Coolant Exit Temperature] [Loop 1 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC91;           //STATE_VAR [TC91] [User] []
		SIM_DATA *m_sdTC92;           //STATE_VAR [Loop1 Region 9 Coolant Exit Temperature] [Loop 1 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC101;           //STATE_VAR [TC101] [User] []
		SIM_DATA *m_sdTC102;           //STATE_VAR [Loop1 Region 10 Coolant Exit Temperature] [Loop 1 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTP2;           //STATE_VAR [TP2] [User] []
		SIM_DATA *m_sdTT1;           //STATE_VAR [TT1] [User] []
		SIM_DATA *m_sdTT2;           //STATE_VAR [TT2] [User] []
		SIM_DATA *m_sdTS1;           //STATE_VAR [TS1] [User] []
		SIM_DATA *m_sdTS2;           //STATE_VAR [TS2] [User] []
		SIM_DATA *m_sdTT;           //STATE_VAR [TT] [User] []
		SIM_DATA *m_sdTS;           //STATE_VAR [TS] [User] []
		SIM_DATA *m_sdHSOUT;           //STATE_VAR [HSOUT] [User] []
		SIM_DATA *m_sdHTOUT;           //STATE_VAR [HTOUT] [User] []
		SIM_DATA *m_sdHCOUT;           //STATE_VAR [HCOUT] [User] []
		SIM_DATA *m_sdTL211;           //STATE_VAR [TL211] [User] []
		SIM_DATA *m_sdVL211;           //STATE_VAR [VL211] [User] []
		SIM_DATA *m_sdTL212;           //STATE_VAR [Loop 2 Region 1 Boundary Layer Exit Temperature] [Loop 2 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL212;           //STATE_VAR [VL212] [User] []
		SIM_DATA *m_sdTW21;           //STATE_VAR [TW21] [User] []
		SIM_DATA *m_sdTL221;           //STATE_VAR [TL221] [User] []
		SIM_DATA *m_sdVL221;           //STATE_VAR [VL221] [User] []
		SIM_DATA *m_sdTL222;           //STATE_VAR [Loop 2 Region 2 Boundary Layer Exit Temperature] [Loop 2 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL222;           //STATE_VAR [VL222] [User] []
		SIM_DATA *m_sdTW22;           //STATE_VAR [TW22] [User] []
		SIM_DATA *m_sdTL231;           //STATE_VAR [TL231] [User] []
		SIM_DATA *m_sdVL231;           //STATE_VAR [VL231] [User] []
		SIM_DATA *m_sdTL232;           //STATE_VAR [Loop 2 Region 3 Boundary Layer Exit Temperature] [Loop 2 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL232;           //STATE_VAR [VL232] [User] []
		SIM_DATA *m_sdTW23;           //STATE_VAR [TW23] [User] []
		SIM_DATA *m_sdTL241;           //STATE_VAR [TL241] [User] []
		SIM_DATA *m_sdVL241;           //STATE_VAR [VL241] [User] []
		SIM_DATA *m_sdTL242;           //STATE_VAR [Loop 2 Region 4 Boundary Layer Exit Temperature] [Loop 2 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL242;           //STATE_VAR [VL242] [User] []
		SIM_DATA *m_sdTW24;           //STATE_VAR [TW24] [User] []
		SIM_DATA *m_sdTL251;           //STATE_VAR [TL251] [User] []
		SIM_DATA *m_sdVL251;           //STATE_VAR [VL251] [User] []
		SIM_DATA *m_sdTL252;           //STATE_VAR [Loop 2 Region 5 Boundary Layer Exit Temperature] [Loop 2 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL252;           //STATE_VAR [VL252] [User] []
		SIM_DATA *m_sdTW25;           //STATE_VAR [TW25] [User] []
		SIM_DATA *m_sdTL261;           //STATE_VAR [TL261] [User] []
		SIM_DATA *m_sdVL261;           //STATE_VAR [VL261] [User] []
		SIM_DATA *m_sdTL262;           //STATE_VAR [Loop 2 Region 6 Boundary Layer Exit Temperature] [Loop 2 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL262;           //STATE_VAR [VL262] [User] []
		SIM_DATA *m_sdTW26;           //STATE_VAR [TW26] [User] []
		SIM_DATA *m_sdTL271;           //STATE_VAR [TL271] [User] []
		SIM_DATA *m_sdVL271;           //STATE_VAR [VL271] [User] []
		SIM_DATA *m_sdTL272;           //STATE_VAR [Loop 2 Region 7 Boundary Layer Exit Temperature] [Loop 2 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL272;           //STATE_VAR [VL272] [User] []
		SIM_DATA *m_sdTW27;           //STATE_VAR [TW27] [User] []
		SIM_DATA *m_sdTL281;           //STATE_VAR [TL281] [User] []
		SIM_DATA *m_sdVL281;           //STATE_VAR [VL281] [User] []
		SIM_DATA *m_sdTL282;           //STATE_VAR [Loop 2 Region 8 Boundary Layer Exit Temperature] [Loop 2 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL282;           //STATE_VAR [VL282] [User] []
		SIM_DATA *m_sdTW28;           //STATE_VAR [TW28] [User] []
		SIM_DATA *m_sdTL291;           //STATE_VAR [TL291] [User] []
		SIM_DATA *m_sdVL291;           //STATE_VAR [VL291] [User] []
		SIM_DATA *m_sdTL292;           //STATE_VAR [Loop 2 Region 9 Boundary Layer Exit Temperature] [Loop 2 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL292;           //STATE_VAR [VL292] [User] []
		SIM_DATA *m_sdTW29;           //STATE_VAR [TW29] [User] []
		SIM_DATA *m_sdTL2101;           //STATE_VAR [TL2101] [User] []
		SIM_DATA *m_sdVL2101;           //STATE_VAR [VL2101] [User] []
		SIM_DATA *m_sdTL2102;           //STATE_VAR [Loop 2 Region 10 Boundary Layer Exit Temperature] [Loop 2 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL2102;           //STATE_VAR [VL2102] [User] []
		SIM_DATA *m_sdTW210;           //STATE_VAR [TW210] [User] []
		SIM_DATA *m_sdTC211;           //STATE_VAR [TC211] [User] []
		SIM_DATA *m_sdTC212;           //STATE_VAR [Loop 2 Region 1 Coolant Outlet Temperature] [Loop 2 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC221;           //STATE_VAR [TC221] [User] []
		SIM_DATA *m_sdTC222;           //STATE_VAR [Loop 2 Region 2 Coolant Outlet Temperature] [Loop 2 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC231;           //STATE_VAR [TC231] [User] []
		SIM_DATA *m_sdTC232;           //STATE_VAR [Loop 2 Region 3 Coolant Outlet Temperature] [Loop 2 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC241;           //STATE_VAR [TC241] [User] []
		SIM_DATA *m_sdTC242;           //STATE_VAR [Loop 2 Region 4 Coolant Outlet Temperature] [Loop 2 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC251;           //STATE_VAR [TC251] [User] []
		SIM_DATA *m_sdTC252;           //STATE_VAR [Loop 2 Region 5 Coolant Outlet Temperature] [Loop 2 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC261;           //STATE_VAR [TC261] [User] []
		SIM_DATA *m_sdTC262;           //STATE_VAR [Loop 2 Region 6 Coolant Outlet Temperature] [Loop 2 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC271;           //STATE_VAR [TC271] [User] []
		SIM_DATA *m_sdTC272;           //STATE_VAR [Loop 2 Region 7 Coolant Outlet Temperature] [Loop 2 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC281;           //STATE_VAR [TC281] [User] []
		SIM_DATA *m_sdTC282;           //STATE_VAR [Loop 2 Region 8 Coolant Outlet Temperature] [Loop 2 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC291;           //STATE_VAR [TC291] [User] []
		SIM_DATA *m_sdTC292;           //STATE_VAR [Loop 2 Region 9 Coolant Outlet Temperature] [Loop 2 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC2101;           //STATE_VAR [TC2101] [User] []
		SIM_DATA *m_sdTC2102;           //STATE_VAR [Loop 2 Region 10 Coolant Outlet Temperature] [Loop 2 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTL311;           //STATE_VAR [TL311] [User] []
		SIM_DATA *m_sdVL311;           //STATE_VAR [VL311] [User] []
		SIM_DATA *m_sdTL312;           //STATE_VAR [Loop 3 Region 1 Boundary Layer Exit Temperature] [Loop 3 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL312;           //STATE_VAR [VL312] [User] []
		SIM_DATA *m_sdTW31;           //STATE_VAR [TW31] [User] []
		SIM_DATA *m_sdTL321;           //STATE_VAR [TL321] [User] []
		SIM_DATA *m_sdVL321;           //STATE_VAR [VL321] [User] []
		SIM_DATA *m_sdTL322;           //STATE_VAR [Loop 3 Region 2 Boundary Layer Exit Temperature] [Loop 3 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL322;           //STATE_VAR [VL322] [User] []
		SIM_DATA *m_sdTW32;           //STATE_VAR [TW32] [User] []
		SIM_DATA *m_sdTL331;           //STATE_VAR [TL331] [User] []
		SIM_DATA *m_sdVL331;           //STATE_VAR [VL331] [User] []
		SIM_DATA *m_sdTL332;           //STATE_VAR [Loop 3 Region 3 Boundary Layer Exit Temperature] [Loop 3 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL332;           //STATE_VAR [VL332] [User] []
		SIM_DATA *m_sdTW33;           //STATE_VAR [TW33] [User] []
		SIM_DATA *m_sdTL341;           //STATE_VAR [TL341] [User] []
		SIM_DATA *m_sdVL341;           //STATE_VAR [VL341] [User] []
		SIM_DATA *m_sdTL342;           //STATE_VAR [Loop 3 Region 4 Boundary Layer Exit Temperature] [Loop 3 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL342;           //STATE_VAR [VL342] [User] []
		SIM_DATA *m_sdTW34;           //STATE_VAR [TW34] [User] []
		SIM_DATA *m_sdTL351;           //STATE_VAR [TL351] [User] []
		SIM_DATA *m_sdVL351;           //STATE_VAR [VL351] [User] []
		SIM_DATA *m_sdTL352;           //STATE_VAR [Loop 3 Region 5 Boundary Layer Exit Temperature] [Loop 3 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL352;           //STATE_VAR [VL352] [User] []
		SIM_DATA *m_sdTW35;           //STATE_VAR [TW35] [User] []
		SIM_DATA *m_sdTL361;           //STATE_VAR [TL361] [User] []
		SIM_DATA *m_sdVL361;           //STATE_VAR [VL361] [User] []
		SIM_DATA *m_sdTL362;           //STATE_VAR [Loop 3 Region 6 Boundary Layer Exit Temperature] [Loop 3 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL362;           //STATE_VAR [VL362] [User] []
		SIM_DATA *m_sdTW36;           //STATE_VAR [TW36] [User] []
		SIM_DATA *m_sdTL371;           //STATE_VAR [TL371] [User] []
		SIM_DATA *m_sdVL371;           //STATE_VAR [VL371] [User] []
		SIM_DATA *m_sdTL372;           //STATE_VAR [Loop 3 Region 7 Boundary Layer Exit Temperature] [Loop 3 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL372;           //STATE_VAR [VL372] [User] []
		SIM_DATA *m_sdTW37;           //STATE_VAR [TW37] [User] []
		SIM_DATA *m_sdTL381;           //STATE_VAR [TL381] [User] []
		SIM_DATA *m_sdVL381;           //STATE_VAR [VL381] [User] []
		SIM_DATA *m_sdTL382;           //STATE_VAR [Loop 3 Region 8 Boundary Layer Exit Temperature] [Loop 3 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL382;           //STATE_VAR [VL382] [User] []
		SIM_DATA *m_sdTW38;           //STATE_VAR [TW38] [User] []
		SIM_DATA *m_sdTL391;           //STATE_VAR [TL391] [User] []
		SIM_DATA *m_sdVL391;           //STATE_VAR [VL391] [User] []
		SIM_DATA *m_sdTL392;           //STATE_VAR [Loop 3 Region 9 Boundary Layer Exit Temperature] [Loop 3 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL392;           //STATE_VAR [VL392] [User] []
		SIM_DATA *m_sdTW39;           //STATE_VAR [TW39] [User] []
		SIM_DATA *m_sdTL3101;           //STATE_VAR [TL3101] [User] []
		SIM_DATA *m_sdVL3101;           //STATE_VAR [VL3101] [User] []
		SIM_DATA *m_sdTL3102;           //STATE_VAR [Loop 3 Region 10 Boundary Layer Exit Temperature] [Loop 3 Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL3102;           //STATE_VAR [VL3102] [User] []
		SIM_DATA *m_sdTW310;           //STATE_VAR [TW310] [User] []
		SIM_DATA *m_sdTC311;           //STATE_VAR [TC311] [User] []
		SIM_DATA *m_sdTC312;           //STATE_VAR [Loop 3 Region 1 Coolant Outlet Temperature] [Loop 3 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC321;           //STATE_VAR [TC321] [User] []
		SIM_DATA *m_sdTC322;           //STATE_VAR [Loop 3 Region 2 Coolant Outlet Temperature] [Loop 3 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC331;           //STATE_VAR [TC331] [User] []
		SIM_DATA *m_sdTC332;           //STATE_VAR [Loop 3 Region 3 Coolant Outlet Temperature] [Loop 3 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC341;           //STATE_VAR [TC341] [User] []
		SIM_DATA *m_sdTC342;           //STATE_VAR [Loop 3 Region 4 Coolant Outlet Temperature] [Loop 3 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC351;           //STATE_VAR [TC351] [User] []
		SIM_DATA *m_sdTC352;           //STATE_VAR [Loop 3 Region 5 Coolant Outlet Temperature] [Loop 3 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC361;           //STATE_VAR [TC361] [User] []
		SIM_DATA *m_sdTC362;           //STATE_VAR [Loop 3 Region 6 Coolant Outlet Temperature] [Loop 3 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC371;           //STATE_VAR [TC371] [User] []
		SIM_DATA *m_sdTC372;           //STATE_VAR [Loop 3 Region 7 Coolant Outlet Temperature] [Loop 3 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC381;           //STATE_VAR [TC381] [User] []
		SIM_DATA *m_sdTC382;           //STATE_VAR [Loop 3 Region 8 Coolant Outlet Temperature] [Loop 3 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC391;           //STATE_VAR [TC391] [User] []
		SIM_DATA *m_sdTC392;           //STATE_VAR [Loop 3 Region 9 Coolant Outlet Temperature] [Loop 3 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC3101;           //STATE_VAR [TC3101] [User] []
		SIM_DATA *m_sdTC3102;           //STATE_VAR [Loop 3 Region 10 Coolant Outlet Temperature] [Loop 3 Coolant Temperature Profile] [C]
		SIM_DATA *m_sdWF;           //STATE_VAR [WF] [User] []
		SIM_DATA *m_sdMDH21;           //STATE_VAR [MDH21] [User] []
		SIM_DATA *m_sdMDO21;           //STATE_VAR [MDO21] [User] []
		SIM_DATA *m_sdVGH1;           //STATE_VAR [Region 1 H2 Volume] [H2 Volume Profile] [m3]
		SIM_DATA *m_sdVGO1;           //STATE_VAR [Region 1 O2 Volume] [O2 Volume Profile] [m3]
		SIM_DATA *m_sdMDH22;           //STATE_VAR [MDH22] [User] []
		SIM_DATA *m_sdMDO22;           //STATE_VAR [MDO22] [User] []
		SIM_DATA *m_sdVGH2;           //STATE_VAR [Region 2 H2 Volume] [H2 Volume Profile] [m3]
		SIM_DATA *m_sdVGO2;           //STATE_VAR [Region 2 O2 Volume] [O2 Volume Profile] [m3]
		SIM_DATA *m_sdMDH23;           //STATE_VAR [MDH23] [User] []
		SIM_DATA *m_sdMDO23;           //STATE_VAR [MDO23] [User] []
		SIM_DATA *m_sdVGH3;           //STATE_VAR [Region 3 H2 Volume] [H2 Volume Profile] [m3]
		SIM_DATA *m_sdVGO3;           //STATE_VAR [Region 3 O2 Volume] [O2 Volume Profile] [m3]
		SIM_DATA *m_sdMDH24;           //STATE_VAR [MDH24] [User] []
		SIM_DATA *m_sdMDO24;           //STATE_VAR [MDO24] [User] []
		SIM_DATA *m_sdVGH4;           //STATE_VAR [Region 4 H2 Volume] [H2 Volume Profile] [m3]
		SIM_DATA *m_sdVGO4;           //STATE_VAR [Region 4 O2 Volume] [O2 Volume Profile] [m3]
		SIM_DATA *m_sdMDH25;           //STATE_VAR [MDH25] [User] []
		SIM_DATA *m_sdMDO25;           //STATE_VAR [MDO25] [User] []
		SIM_DATA *m_sdVGH5;           //STATE_VAR [Region 5 H2 Volume] [H2 Volume Profile] [m3]
		SIM_DATA *m_sdVGO5;           //STATE_VAR [Region 5 O2 Volume] [O2 Volume Profile] [m3]
		SIM_DATA *m_sdMDH26;           //STATE_VAR [MDH26] [User] []
		SIM_DATA *m_sdMDO26;           //STATE_VAR [MDO26] [User] []
		SIM_DATA *m_sdVGH6;           //STATE_VAR [Region 6 H2 Volume] [H2 Volume Profile] [m3]
		SIM_DATA *m_sdVGO6;           //STATE_VAR [Region 6 O2 Volume] [O2 Volume Profile] [m3]
		SIM_DATA *m_sdMDH27;           //STATE_VAR [MDH27] [User] []
		SIM_DATA *m_sdMDO27;           //STATE_VAR [MDO27] [User] []
		SIM_DATA *m_sdVGH7;           //STATE_VAR [Region 7 H2 Volume] [H2 Volume Profile] [m3]
		SIM_DATA *m_sdVGO7;           //STATE_VAR [Region 7 O2 Volume] [O2 Volume Profile] [m3]
		SIM_DATA *m_sdMDH28;           //STATE_VAR [MDH28] [User] []
		SIM_DATA *m_sdMDO28;           //STATE_VAR [MDO28] [User] []
		SIM_DATA *m_sdVGH8;           //STATE_VAR [Region 8 H2 Volume] [H2 Volume Profile] [m3]
		SIM_DATA *m_sdVGO8;           //STATE_VAR [Region 8 O2 Volume] [O2 Volume Profile] [m3]
		SIM_DATA *m_sdMDH29;           //STATE_VAR [MDH29] [User] []
		SIM_DATA *m_sdMDO29;           //STATE_VAR [MDO29] [User] []
		SIM_DATA *m_sdVGH9;           //STATE_VAR [Region 9 H2 Volume] [H2 Volume Profile] [m3]
		SIM_DATA *m_sdVGO9;           //STATE_VAR [Region 9 O2 Volume] [O2 Volume Profile] [m3]
		SIM_DATA *m_sdMDH210;           //STATE_VAR [MDH210] [User] []
		SIM_DATA *m_sdMDO210;           //STATE_VAR [MDO210] [User] []
		SIM_DATA *m_sdVGH10;           //STATE_VAR [Region 10 H2 Volume] [H2 Volume Profile] [m3]
		SIM_DATA *m_sdVGO10;           //STATE_VAR [Region 10 O2 Volume] [O2 Volume Profile] [m3]
		SIM_DATA *m_sdHP;           //STATE_VAR [HP] [User] []
		SIM_DATA *m_sdOP;           //STATE_VAR [OP] [User] []
		SIM_DATA *m_sdVOGO;           //STATE_VAR [VOGO] [User] []
		SIM_DATA *m_sdVNI;           //STATE_VAR [VNI] [User] []
		SIM_DATA *m_sdWMU;           //STATE_VAR [WMU] [User] []
		SIM_DATA *m_sdVP;           //STATE_VAR [VP] [User] []
		SIM_DATA *m_sdTP;           //STATE_VAR [TP] [User] []
		SIM_DATA *m_sdHEATIN;           //STATE_VAR [HEATIN] [User] []
		SIM_DATA *m_sdHEATOUT;           //STATE_VAR [HEATOUT] [User] []
		SIM_DATA *m_sdUP;           //STATE_VAR [UP] [User] []
		SIM_DATA *m_sdWORK;           //STATE_VAR [WORK] [User] []
		SIM_DATA *m_sdMHY;           //STATE_VAR [MHY] [User] []
		SIM_DATA *m_sdPH;           //STATE_VAR [PH] [User] []
		SIM_DATA *m_sdMOX;           //STATE_VAR [MOX] [User] []
		SIM_DATA *m_sdPO;           //STATE_VAR [PO] [User] []
		SIM_DATA *m_sdMN;           //STATE_VAR [MN] [User] []
		SIM_DATA *m_sdPN;           //STATE_VAR [PN] [User] []
		SIM_DATA *m_sdE;           //STATE_VAR [E] [User] []
	private:
		SIM_DATA m_sdConstBase;
		//define CONST here
		SIM_DATA m_sdRG;           //CONST [] [Constant] []
		SIM_DATA m_sdHM;           //CONST [] [Constant] []
		SIM_DATA m_sdOM;           //CONST [] [Constant] []
		SIM_DATA m_sdNM;           //CONST [] [Constant] []
		SIM_DATA m_sdPI;           //CONST [] [Constant] []
		SIM_DATA m_sdUM;           //CONST [] [Constant] []
		SIM_DATA m_sdAN;           //CONST [] [Constant] []
		SIM_DATA m_sdkB;           //CONST [] [Constant] []
		SIM_DATA m_sdnmass;           //CONST [] [Constant] []
		SIM_DATA m_sdAL1;           //CONST [] [Constant] []
		SIM_DATA m_sdF1;           //CONST [] [Constant] []
		SIM_DATA m_sdAL2;           //CONST [] [Constant] []
		SIM_DATA m_sdF2;           //CONST [] [Constant] []
		SIM_DATA m_sdAL3;           //CONST [] [Constant] []
		SIM_DATA m_sdF3;           //CONST [] [Constant] []
		SIM_DATA m_sdAL4;           //CONST [] [Constant] []
		SIM_DATA m_sdF4;           //CONST [] [Constant] []
		SIM_DATA m_sdAL5;           //CONST [] [Constant] []
		SIM_DATA m_sdF5;           //CONST [] [Constant] []
		SIM_DATA m_sdAL6;           //CONST [] [Constant] []
		SIM_DATA m_sdF6;           //CONST [] [Constant] []
		SIM_DATA m_sdHfg;           //CONST [Energy Density of Fuel] [Physical Parameters] [MJ/kg]
		SIM_DATA m_sdsvg;           //CONST [] [Constant] []
		SIM_DATA m_sdHg;           //CONST [] [Constant] []
		SIM_DATA m_sdXT;           //CONST [] [Constant] []
		SIM_DATA m_sdV0;           //CONST [Initial Core Volume] [Core Configuration] [m3]
		SIM_DATA m_sdHCORE;           //CONST [Initial Core Height] [Core Configuration] [m]
		SIM_DATA m_sdVP0;           //CONST [Initial Plenum Volume] [Core Configuration] [m3]
		SIM_DATA m_sdCC1R;           //CONST [Inner Channel Wall Inner Radius] [Core Configuration] [cm]
		SIM_DATA m_sdCC1WT;           //CONST [Inner Channel Wall Thickness] [Core Configuration] [cm]
		SIM_DATA m_sdCC2R;           //CONST [] [Constant] []
		SIM_DATA m_sdCC1T;           //CONST [Inner Channel Thickness] [Core Configuration] [cm]
		SIM_DATA m_sdCC3R;           //CONST [] [Constant] []
		SIM_DATA m_sdCC4R;           //CONST [] [Constant] []
		SIM_DATA m_sdXSA1;           //CONST [] [Constant] []
		SIM_DATA m_sdCC1V;           //CONST [] [Constant] []
		SIM_DATA m_sdCC1WV;           //CONST [] [Constant] []
		SIM_DATA m_sdCC1D;           //CONST [Inner Channel Wall Material Density] [Core Configuration] [kg/m3]
		SIM_DATA m_sdCC1M;           //CONST [] [Constant] []
		SIM_DATA m_sdTID;           //CONST [Cooling Tube Interior Diameter] [Core Configuration] [cm]
		SIM_DATA m_sdTWT;           //CONST [Cooling Tube Wall Thickness] [Core Configuration] [cm]
		SIM_DATA m_sdTOD;           //CONST [] [Constant] []
		SIM_DATA m_sdXSAT;           //CONST [] [Constant] []
		SIM_DATA m_sdTNUM;           //CONST [Number of Cooling Tubes] [Core Configuration] []
		SIM_DATA m_sdCCTV;           //CONST [] [Constant] []
		SIM_DATA m_sdCCTWV;           //CONST [] [Constant] []
		SIM_DATA m_sdCCTD;           //CONST [Cooling Tube Wall Material Density] [Core Configuration] [kg/m3]
		SIM_DATA m_sdCCTM;           //CONST [] [Constant] []
		SIM_DATA m_sdCC5R;           //CONST [Outer Channel Outer Radius] [Core Configuration] [cm]
		SIM_DATA m_sdCC2WT;           //CONST [Outer Channel Wall Thickness] [Core Configuration] [cm]
		SIM_DATA m_sdCC6R;           //CONST [] [Constant] []
		SIM_DATA m_sdCC2T;           //CONST [Outer Channel Thickness] [Core Configuration] [cm]
		SIM_DATA m_sdCC7R;           //CONST [] [Constant] []
		SIM_DATA m_sdCC8R;           //CONST [] [Constant] []
		SIM_DATA m_sdXSA2;           //CONST [] [Constant] []
		SIM_DATA m_sdCC2V;           //CONST [] [Constant] []
		SIM_DATA m_sdCC2WV;           //CONST [] [Constant] []
		SIM_DATA m_sdCC2D;           //CONST [Outer Channel Wall Material Density] [Core Configuration] [kg/m3]
		SIM_DATA m_sdCC2M;           //CONST [] [Constant] []
		SIM_DATA m_sdTCCV;           //CONST [] [Constant] []
		SIM_DATA m_sdTOTCM;           //CONST [] [Constant] []
		SIM_DATA m_sdCC1MF;           //CONST [] [Constant] []
		SIM_DATA m_sdCCTMF;           //CONST [] [Constant] []
		SIM_DATA m_sdCC2MF;           //CONST [] [Constant] []
		SIM_DATA m_sdMCLUMP;           //CONST [] [Constant] []
		SIM_DATA m_sdMCLUMP2;           //CONST [] [Constant] []
		SIM_DATA m_sdMCLUMP3;           //CONST [] [Constant] []
		SIM_DATA m_sdHDia1;           //CONST [] [Constant] []
		SIM_DATA m_sdHDia2;           //CONST [] [Constant] []
		SIM_DATA m_sdHDia3;           //CONST [] [Constant] []
		SIM_DATA m_sdWTR1;           //CONST [] [Constant] []
		SIM_DATA m_sdWTR2;           //CONST [] [Constant] []
		SIM_DATA m_sdWTR3;           //CONST [] [Constant] []
		SIM_DATA m_sdSAL1F;           //CONST [] [Constant] []
		SIM_DATA m_sdSAL1C;           //CONST [] [Constant] []
		SIM_DATA m_sdSAL2F;           //CONST [] [Constant] []
		SIM_DATA m_sdSAL2C;           //CONST [] [Constant] []
		SIM_DATA m_sdSAL3F;           //CONST [] [Constant] []
		SIM_DATA m_sdSAL3C;           //CONST [] [Constant] []
		SIM_DATA m_sdTWC;           //CONST [Coolant Mass Flow] [Operational Parameters] [kg/s]
		SIM_DATA m_sdTXSA;           //CONST [] [Constant] []
		SIM_DATA m_sdXSA1f;           //CONST [] [Constant] []
		SIM_DATA m_sdXSATf;           //CONST [] [Constant] []
		SIM_DATA m_sdXSA2f;           //CONST [] [Constant] []
		SIM_DATA m_sdALF;           //CONST [Core Averaged Temperature Coefficient of Reactivity] [Reactivity Parameters] [$/C]
		SIM_DATA m_sdPHI;           //CONST [Core Averaged Void Coefficient of Reactivity] [Reactivity Parameters] [$]
		SIM_DATA m_sdFRA10;           //CONST [Fission Fraction for Region 10] [Reactivity Parameters] []
		SIM_DATA m_sdFRA9;           //CONST [Fission Fraction for Region 9] [Reactivity Parameters] []
		SIM_DATA m_sdFRA8;           //CONST [Fission Fraction for Region 8] [Reactivity Parameters] []
		SIM_DATA m_sdFRA7;           //CONST [Fission Fraction for Region 7] [Reactivity Parameters] []
		SIM_DATA m_sdFRA6;           //CONST [Fission Fraction for Region 6] [Reactivity Parameters] []
		SIM_DATA m_sdFRA5;           //CONST [Fission Fraction for Region 5] [Reactivity Parameters] []
		SIM_DATA m_sdFRA4;           //CONST [Fission Fraction for Region 4] [Reactivity Parameters] []
		SIM_DATA m_sdFRA3;           //CONST [Fission Fraction for Region 3] [Reactivity Parameters] []
		SIM_DATA m_sdFRA2;           //CONST [Fission Fraction for Region 2] [Reactivity Parameters] []
		SIM_DATA m_sdFRA1;           //CONST [Fission Fraction for Region 1] [Reactivity Parameters] []
		SIM_DATA m_sdI10;           //CONST [Importance Factor for Region 10] [Reactivity Parameters] []
		SIM_DATA m_sdI9;           //CONST [Importance Factor for Region 9] [Reactivity Parameters] []
		SIM_DATA m_sdI8;           //CONST [Importance Factor for Region 8] [Reactivity Parameters] []
		SIM_DATA m_sdI7;           //CONST [Importance Factor for Region 7] [Reactivity Parameters] []
		SIM_DATA m_sdI6;           //CONST [Importance Factor for Region 6] [Reactivity Parameters] []
		SIM_DATA m_sdI5;           //CONST [Importance Factor for Region 5] [Reactivity Parameters] []
		SIM_DATA m_sdI4;           //CONST [Importance Factor for Region 4] [Reactivity Parameters] []
		SIM_DATA m_sdI3;           //CONST [Importance Factor for Region 3] [Reactivity Parameters] []
		SIM_DATA m_sdI2;           //CONST [Importance Factor for Region 2] [Reactivity Parameters] []
		SIM_DATA m_sdI1;           //CONST [Importance Factor for Region 1] [Reactivity Parameters] []
		SIM_DATA m_sdTAU;           //CONST [Average Gas Bubble Transit Time] [Reactivity Parameters] [s]
		SIM_DATA m_sdTAUS;           //CONST [] [Constant] []
		SIM_DATA m_sdT0;           //CONST [Initial Fuel Temperature] [Operational Parameters] [C]
		SIM_DATA m_sdTC0;           //CONST [Initial Coolant Temperature] [Operational Parameters] [C]
		SIM_DATA m_sdFE;           //CONST [Fuel Enrichment] [Operational Parameters] []
		SIM_DATA m_sdFC;           //CONST [Uranium Concentration of Fuel] [Operational Parameters] [g/l]
		SIM_DATA m_sdCV;           //CONST [Specific Heat of Fuel] [Physical Parameters] []
		SIM_DATA m_sdA;           //CONST [Initial Power] [Reactivity Parameters] [$]
		SIM_DATA m_sdMNT;           //CONST [Mean Neutron Generation Time] [Reactivity Parameters] [s]
		SIM_DATA m_sdBETA;           //CONST [Delayed Neutron Fraction] [Reactivity Parameters] []
		SIM_DATA m_sdBOL;           //CONST [] [Constant] []
		SIM_DATA m_sdQ0;           //CONST [Intrinsic Neutron Source] [Operational Parameters] [s-1]
		SIM_DATA m_sdEN0;           //CONST [] [Constant] []
		SIM_DATA m_sdAccSS;           //CONST [Accelerator Output] [Operational Parameters] []
		SIM_DATA m_sdAccOnTime;           //CONST [Accelerator on time] [Operational Parameters] [s]
		SIM_DATA m_sdAccOffTime;           //CONST [Accelerator off time] [Operational Parameters] [s]
		SIM_DATA m_sdRRTE;           //CONST [Rate of Reactivity Insertion] [Operational Parameters] [$/s]
		SIM_DATA m_sdFLAG;           //CONST [Point-in-time-of reactivity insertion] [Operational Parameters] [s]
		SIM_DATA m_sdRmax;           //CONST [Total Reactivity Insertion] [Operational Parameters] [$]
		SIM_DATA m_sdCoolOffTime;           //CONST [Off Time of Coolant] [Operational Parameters] [s]
		SIM_DATA m_sdCoolHigh1;           //CONST [Loop 1 Coolant Flow Rate Multiplier] [Operational Parameters] []
		SIM_DATA m_sdCoolHigh2;           //CONST [Loop 2 Coolant Flow Rate Multiplier] [Operational Parameters] []
		SIM_DATA m_sdCoolHigh3;           //CONST [Loop 3 Coolant Flow Rate Multiplier] [Operational Parameters] []
		SIM_DATA m_sdPP;           //CONST [Plenum Pressure] [Operational Parameters] [atm]
		SIM_DATA m_sdP0;           //CONST [] [Constant] []
		SIM_DATA m_sdTB;           //CONST [] [Constant] []
		SIM_DATA m_sdTMAX;           //CONST [] [Constant] []
		SIM_DATA m_sdNN;           //CONST [] [Constant] []
		SIM_DATA m_sdscale;           //CONST [] [Constant] []
		SIM_DATA m_sdLI;           //CONST [] [Constant] []
		SIM_DATA m_sdBL;           //CONST [Boundary Layer Thickness] [Physical Parameters] [m]
		SIM_DATA m_sdCTR;           //CONST [] [Constant] []
		SIM_DATA m_sdALI;           //CONST [] [Constant] []
		SIM_DATA m_sdALO;           //CONST [] [Constant] []
		SIM_DATA m_sdALOOP1;           //CONST [] [Constant] []
		SIM_DATA m_sdALOOP2;           //CONST [] [Constant] []
		SIM_DATA m_sdALOOP3;           //CONST [] [Constant] []
		SIM_DATA m_sdALOOPT;           //CONST [] [Constant] []
		SIM_DATA m_sdAL;           //CONST [] [Constant] []
		SIM_DATA m_sdAC;           //CONST [] [Constant] []
		SIM_DATA m_sdVLAYER;           //CONST [] [Constant] []
		SIM_DATA m_sdVL;           //CONST [] [Constant] []
		SIM_DATA m_sdVL2;           //CONST [] [Constant] []
		SIM_DATA m_sdVL3;           //CONST [] [Constant] []
		SIM_DATA m_sdMH2;           //CONST [] [Constant] []
		SIM_DATA m_sdMO2;           //CONST [] [Constant] []
		SIM_DATA m_sdTAU2;           //CONST [] [Constant] []
		SIM_DATA m_sdPHI1;           //CONST [] [Constant] []
		SIM_DATA m_sdPHI2;           //CONST [] [Constant] []
		SIM_DATA m_sdPHI3;           //CONST [] [Constant] []
		SIM_DATA m_sdPHI4;           //CONST [] [Constant] []
		SIM_DATA m_sdPHI5;           //CONST [] [Constant] []
		SIM_DATA m_sdPHI6;           //CONST [] [Constant] []
		SIM_DATA m_sdPHI7;           //CONST [] [Constant] []
		SIM_DATA m_sdPHI8;           //CONST [] [Constant] []
		SIM_DATA m_sdPHI9;           //CONST [] [Constant] []
		SIM_DATA m_sdPHI10;           //CONST [] [Constant] []
		SIM_DATA m_sdBR1;           //CONST [] [Constant] []
		SIM_DATA m_sdBR2;           //CONST [] [Constant] []
		SIM_DATA m_sdBR3;           //CONST [] [Constant] []
		SIM_DATA m_sdBR4;           //CONST [] [Constant] []
		SIM_DATA m_sdBR5;           //CONST [] [Constant] []
		SIM_DATA m_sdBR6;           //CONST [] [Constant] []
		SIM_DATA m_sdBR7;           //CONST [] [Constant] []
		SIM_DATA m_sdBR8;           //CONST [] [Constant] []
		SIM_DATA m_sdBR9;           //CONST [] [Constant] []
		SIM_DATA m_sdBR10;           //CONST [] [Constant] []
		SIM_DATA m_sdTC1IN;           //CONST [] [Constant] []
		SIM_DATA m_sdTS1IN;           //CONST [] [Constant] []
		SIM_DATA m_sdAIR;           //CONST [] [Constant] []
		SIM_DATA m_sdRNI;           //CONST [] [Constant] []
		SIM_DATA m_sdROI;           //CONST [] [Constant] []
	};
}
