#pragma once
#include "SimDll13.h"

namespace Sim
{

	class SIMDLL_EXPORTS SupoModel : public Model
	{
	public:
		SupoModel();
		~SupoModel();
		void SetModelParameters();
		void InitializeModelVars();

		void ModelDerivatives(int iCol);
		SIM_DATA* Base(){ return &m_sdBase; }
		SIM_DATA* ConstBase(){ return &m_sdConstBase; }
		char* Name(){ return "SupoModel";}
		int StateSize(){ return 177;}
		int NonStateSize(){ return 464;}
		int ConstSize(){ return 112;}
		SIM_DATA YScale(){ return m_sdscale;}
		int NumCustIcTabs(){ return 4;}

		//FUNCTIONS


		//SUBMODELS


	private:
		SIM_DATA m_sdBase;
		//define NS_VARS here
		SIM_DATA m_sdPDOT;           //NS_VAR [PDOT] [User] []
		SIM_DATA m_sdBOL;           //NS_VAR [BOL] [User] []
		SIM_DATA m_sdCUT;           //NS_VAR [CUT] [User] []
		SIM_DATA m_sdRAMP;           //NS_VAR [RAMP] [User] []
		SIM_DATA m_sdTEMP;           //NS_VAR [Average Fuel Temperature] [Performance] [C]
		SIM_DATA m_sdPHI1;           //NS_VAR [PHI1] [User] []
		SIM_DATA m_sdPHI2;           //NS_VAR [PHI2] [User] []
		SIM_DATA m_sdPHI3;           //NS_VAR [PHI3] [User] []
		SIM_DATA m_sdPHI4;           //NS_VAR [PHI4] [User] []
		SIM_DATA m_sdPHI5;           //NS_VAR [PHI5] [User] []
		SIM_DATA m_sdPHI6;           //NS_VAR [PHI6] [User] []
		SIM_DATA m_sdPHI7;           //NS_VAR [PHI7] [User] []
		SIM_DATA m_sdPHI8;           //NS_VAR [PHI8] [User] []
		SIM_DATA m_sdPHI9;           //NS_VAR [PHI9] [User] []
		SIM_DATA m_sdPHI10;           //NS_VAR [PHI10] [User] []
		SIM_DATA m_sdALF1;           //NS_VAR [ALF1] [User] []
		SIM_DATA m_sdALF2;           //NS_VAR [ALF2] [User] []
		SIM_DATA m_sdALF3;           //NS_VAR [ALF3] [User] []
		SIM_DATA m_sdALF4;           //NS_VAR [ALF4] [User] []
		SIM_DATA m_sdALF5;           //NS_VAR [ALF5] [User] []
		SIM_DATA m_sdALF6;           //NS_VAR [ALF6] [User] []
		SIM_DATA m_sdALF7;           //NS_VAR [ALF7] [User] []
		SIM_DATA m_sdALF8;           //NS_VAR [ALF8] [User] []
		SIM_DATA m_sdALF9;           //NS_VAR [ALF9] [User] []
		SIM_DATA m_sdALF10;           //NS_VAR [ALF10] [User] []
		SIM_DATA m_sdRFBA1;           //NS_VAR [RFBA1] [User] []
		SIM_DATA m_sdRFBA2;           //NS_VAR [RFBA2] [User] []
		SIM_DATA m_sdRFBA3;           //NS_VAR [RFBA3] [User] []
		SIM_DATA m_sdRFBA;           //NS_VAR [RFBA] [User] []
		SIM_DATA m_sdVF1;           //NS_VAR [Region 1 Void Fraction] [Radiolytic Gas Profile] []
		SIM_DATA m_sdVF2;           //NS_VAR [Region 2 Void Fraction] [Radiolytic Gas Profile] []
		SIM_DATA m_sdVF3;           //NS_VAR [Region 3 Void Fraction] [Radiolytic Gas Profile] []
		SIM_DATA m_sdVF4;           //NS_VAR [Region 4 Void Fraction] [Radiolytic Gas Profile] []
		SIM_DATA m_sdVF5;           //NS_VAR [Region 5 Void Fraction] [Radiolytic Gas Profile] []
		SIM_DATA m_sdVF6;           //NS_VAR [Region 6 Void Fraction] [Radiolytic Gas Profile] []
		SIM_DATA m_sdVF7;           //NS_VAR [Region 7 Void Fraction] [Radiolytic Gas Profile] []
		SIM_DATA m_sdVF8;           //NS_VAR [Region 8 Void Fraction] [Radiolytic Gas Profile] []
		SIM_DATA m_sdVF9;           //NS_VAR [Region 9 Void Fraction] [Radiolytic Gas Profile] []
		SIM_DATA m_sdVF10;           //NS_VAR [Region 10 Void Fraction] [Radiolytic Gas Profile] []
		SIM_DATA m_sdRFBV1;           //NS_VAR [RFBV1] [User] []
		SIM_DATA m_sdRFBV2;           //NS_VAR [RFBV2] [User] []
		SIM_DATA m_sdRFBV3;           //NS_VAR [RFBV3] [User] []
		SIM_DATA m_sdRFBV;           //NS_VAR [RFBV] [User] []
		SIM_DATA m_sdR;           //NS_VAR [System Reactivity] [Performance] [$]
		SIM_DATA m_sdENP;           //NS_VAR [ENP] [User] []
		SIM_DATA m_sdSUM;           //NS_VAR [SUM] [User] []
		SIM_DATA m_sdENDOT;           //NS_VAR [ENDOT] [User] []
		SIM_DATA m_sdENLOG;           //NS_VAR [ENLOG] [User] []
		SIM_DATA m_sdmXS;           //NS_VAR [mXS] [User] []
		SIM_DATA m_sdVav;           //NS_VAR [Vav] [User] []
		SIM_DATA m_sdSav;           //NS_VAR [Sav] [User] []
		SIM_DATA m_sdFND;           //NS_VAR [FND] [User] []
		SIM_DATA m_sdPCF;           //NS_VAR [PCF] [User] []
		SIM_DATA m_sdkw;           //NS_VAR [Power] [Performance] [kW]
		SIM_DATA m_sdENPMAX;           //NS_VAR [ENPMAX] [User] []
		SIM_DATA m_sdkwmax;           //NS_VAR [Maximum Power] [Performance] [kW]
		SIM_DATA m_sdWC;           //NS_VAR [WC] [User] []
		SIM_DATA m_sdRN1;           //NS_VAR [RN1] [User] []
		SIM_DATA m_sdACT;           //NS_VAR [ACT] [User] []
		SIM_DATA m_sdRN2;           //NS_VAR [RN2] [User] []
		SIM_DATA m_sdTKZ;           //NS_VAR [TKZ] [User] []
		SIM_DATA m_sdTHZ;           //NS_VAR [THZ] [User] []
		SIM_DATA m_sdTWA;           //NS_VAR [TWA] [User] []
		SIM_DATA m_sdTHOT;           //NS_VAR [THOT] [User] []
		SIM_DATA m_sdTCOLD;           //NS_VAR [TCOLD] [User] []
		SIM_DATA m_sdDIA;           //NS_VAR [DIA] [User] []
		SIM_DATA m_sdRay;           //NS_VAR [Ray] [User] []
		SIM_DATA m_sdGr;           //NS_VAR [Gr] [User] []
		SIM_DATA m_sddlta;           //NS_VAR [dlta] [User] []
		SIM_DATA m_sdHTNC;           //NS_VAR [HTNC] [User] []
		SIM_DATA m_sdHT1;           //NS_VAR [HT1] [User] []
		SIM_DATA m_sdHT2;           //NS_VAR [HT2] [User] []
		SIM_DATA m_sdOHM;           //NS_VAR [OHM] [User] []
		SIM_DATA m_sdAREAHT2;           //NS_VAR [AREAHT2] [User] []
		SIM_DATA m_sdGMMA;           //NS_VAR [GMMA] [User] []
		SIM_DATA m_sdGAMMA;           //NS_VAR [GAMMA] [User] []
		SIM_DATA m_sdGAMMA9;           //NS_VAR [GAMMA9] [User] []
		SIM_DATA m_sdST1;           //NS_VAR [ST1] [User] []
		SIM_DATA m_sdTEM1DOT;           //NS_VAR [TEM1DOT] [User] []
		SIM_DATA m_sdVFT1;           //NS_VAR [VFT1] [User] []
		SIM_DATA m_sdRF1;           //NS_VAR [RF1] [User] []
		SIM_DATA m_sdTL11DOT;           //NS_VAR [TL11DOT] [User] []
		SIM_DATA m_sdVLT11;           //NS_VAR [VLT11] [User] []
		SIM_DATA m_sdRL11;           //NS_VAR [RL11] [User] []
		SIM_DATA m_sdTL12DOT;           //NS_VAR [TL12DOT] [User] []
		SIM_DATA m_sdVLT12;           //NS_VAR [VLT12] [User] []
		SIM_DATA m_sdRL12;           //NS_VAR [RL12] [User] []
		SIM_DATA m_sdTL21DOT;           //NS_VAR [TL21DOT] [User] []
		SIM_DATA m_sdVLT21;           //NS_VAR [VLT21] [User] []
		SIM_DATA m_sdRL21;           //NS_VAR [RL21] [User] []
		SIM_DATA m_sdTL22DOT;           //NS_VAR [TL22DOT] [User] []
		SIM_DATA m_sdVLT22;           //NS_VAR [VLT22] [User] []
		SIM_DATA m_sdRL22;           //NS_VAR [RL22] [User] []
		SIM_DATA m_sdTL31DOT;           //NS_VAR [TL31DOT] [User] []
		SIM_DATA m_sdVLT31;           //NS_VAR [VLT31] [User] []
		SIM_DATA m_sdRL31;           //NS_VAR [RL31] [User] []
		SIM_DATA m_sdTL32DOT;           //NS_VAR [TL32DOT] [User] []
		SIM_DATA m_sdVLT32;           //NS_VAR [VLT32] [User] []
		SIM_DATA m_sdRL32;           //NS_VAR [RL32] [User] []
		SIM_DATA m_sdTL41DOT;           //NS_VAR [TL41DOT] [User] []
		SIM_DATA m_sdVLT41;           //NS_VAR [VLT41] [User] []
		SIM_DATA m_sdRL41;           //NS_VAR [RL41] [User] []
		SIM_DATA m_sdTL42DOT;           //NS_VAR [TL42DOT] [User] []
		SIM_DATA m_sdVLT42;           //NS_VAR [VLT42] [User] []
		SIM_DATA m_sdRL42;           //NS_VAR [RL42] [User] []
		SIM_DATA m_sdTL51DOT;           //NS_VAR [TL51DOT] [User] []
		SIM_DATA m_sdVLT51;           //NS_VAR [VLT51] [User] []
		SIM_DATA m_sdRL51;           //NS_VAR [RL51] [User] []
		SIM_DATA m_sdTL52DOT;           //NS_VAR [TL52DOT] [User] []
		SIM_DATA m_sdVLT52;           //NS_VAR [VLT52] [User] []
		SIM_DATA m_sdRL52;           //NS_VAR [RL52] [User] []
		SIM_DATA m_sdTL61DOT;           //NS_VAR [TL61DOT] [User] []
		SIM_DATA m_sdVLT61;           //NS_VAR [VLT61] [User] []
		SIM_DATA m_sdRL61;           //NS_VAR [RL61] [User] []
		SIM_DATA m_sdTL62DOT;           //NS_VAR [TL62DOT] [User] []
		SIM_DATA m_sdVLT62;           //NS_VAR [VLT62] [User] []
		SIM_DATA m_sdRL62;           //NS_VAR [RL62] [User] []
		SIM_DATA m_sdTL71DOT;           //NS_VAR [TL71DOT] [User] []
		SIM_DATA m_sdVLT71;           //NS_VAR [VLT71] [User] []
		SIM_DATA m_sdRL71;           //NS_VAR [RL71] [User] []
		SIM_DATA m_sdTL72DOT;           //NS_VAR [TL72DOT] [User] []
		SIM_DATA m_sdVLT72;           //NS_VAR [VLT72] [User] []
		SIM_DATA m_sdRL72;           //NS_VAR [RL72] [User] []
		SIM_DATA m_sdTL81DOT;           //NS_VAR [TL81DOT] [User] []
		SIM_DATA m_sdVLT81;           //NS_VAR [VLT81] [User] []
		SIM_DATA m_sdRL81;           //NS_VAR [RL81] [User] []
		SIM_DATA m_sdTL82DOT;           //NS_VAR [TL82DOT] [User] []
		SIM_DATA m_sdVLT82;           //NS_VAR [VLT82] [User] []
		SIM_DATA m_sdRL82;           //NS_VAR [RL82] [User] []
		SIM_DATA m_sdTL91DOT;           //NS_VAR [TL91DOT] [User] []
		SIM_DATA m_sdVLT91;           //NS_VAR [VLT91] [User] []
		SIM_DATA m_sdRL91;           //NS_VAR [RL91] [User] []
		SIM_DATA m_sdTL92DOT;           //NS_VAR [TL92DOT] [User] []
		SIM_DATA m_sdVLT92;           //NS_VAR [VLT92] [User] []
		SIM_DATA m_sdRL92;           //NS_VAR [RL92] [User] []
		SIM_DATA m_sdTL101DOT;           //NS_VAR [TL101DOT] [User] []
		SIM_DATA m_sdVLT101;           //NS_VAR [VLT101] [User] []
		SIM_DATA m_sdRL101;           //NS_VAR [RL101] [User] []
		SIM_DATA m_sdTL102DOT;           //NS_VAR [TL102DOT] [User] []
		SIM_DATA m_sdVLT102;           //NS_VAR [VLT102] [User] []
		SIM_DATA m_sdRL102;           //NS_VAR [RL102] [User] []
		SIM_DATA m_sdST2;           //NS_VAR [ST2] [User] []
		SIM_DATA m_sdTEM2DOT;           //NS_VAR [TEM2DOT] [User] []
		SIM_DATA m_sdVFT2;           //NS_VAR [VFT2] [User] []
		SIM_DATA m_sdRF2;           //NS_VAR [RF2] [User] []
		SIM_DATA m_sdST3;           //NS_VAR [ST3] [User] []
		SIM_DATA m_sdTEM3DOT;           //NS_VAR [TEM3DOT] [User] []
		SIM_DATA m_sdVFT3;           //NS_VAR [VFT3] [User] []
		SIM_DATA m_sdRF3;           //NS_VAR [RF3] [User] []
		SIM_DATA m_sdST4;           //NS_VAR [ST4] [User] []
		SIM_DATA m_sdTEM4DOT;           //NS_VAR [TEM4DOT] [User] []
		SIM_DATA m_sdVFT4;           //NS_VAR [VFT4] [User] []
		SIM_DATA m_sdRF4;           //NS_VAR [RF4] [User] []
		SIM_DATA m_sdST5;           //NS_VAR [ST5] [User] []
		SIM_DATA m_sdTEM5DOT;           //NS_VAR [TEM5DOT] [User] []
		SIM_DATA m_sdVFT5;           //NS_VAR [VFT5] [User] []
		SIM_DATA m_sdRF5;           //NS_VAR [RF5] [User] []
		SIM_DATA m_sdST6;           //NS_VAR [ST6] [User] []
		SIM_DATA m_sdTEM6DOT;           //NS_VAR [TEM6DOT] [User] []
		SIM_DATA m_sdVFT6;           //NS_VAR [VFT6] [User] []
		SIM_DATA m_sdRF6;           //NS_VAR [RF6] [User] []
		SIM_DATA m_sdST7;           //NS_VAR [ST7] [User] []
		SIM_DATA m_sdTEM7DOT;           //NS_VAR [TEM7DOT] [User] []
		SIM_DATA m_sdVFT7;           //NS_VAR [VFT7] [User] []
		SIM_DATA m_sdRF7;           //NS_VAR [RF7] [User] []
		SIM_DATA m_sdST8;           //NS_VAR [ST8] [User] []
		SIM_DATA m_sdTEM8DOT;           //NS_VAR [TEM8DOT] [User] []
		SIM_DATA m_sdVFT8;           //NS_VAR [VFT8] [User] []
		SIM_DATA m_sdRF8;           //NS_VAR [RF8] [User] []
		SIM_DATA m_sdST9;           //NS_VAR [ST9] [User] []
		SIM_DATA m_sdTEM9DOT;           //NS_VAR [TEM9DOT] [User] []
		SIM_DATA m_sdVFT9;           //NS_VAR [VFT9] [User] []
		SIM_DATA m_sdRF9;           //NS_VAR [RF9] [User] []
		SIM_DATA m_sdST10;           //NS_VAR [ST10] [User] []
		SIM_DATA m_sdTEM10DT;           //NS_VAR [TEM10DT] [User] []
		SIM_DATA m_sdVFT10;           //NS_VAR [VFT10] [User] []
		SIM_DATA m_sdRF10;           //NS_VAR [RF10] [User] []
		SIM_DATA m_sdSUML1;           //NS_VAR [SUML1] [User] []
		SIM_DATA m_sdSUML2;           //NS_VAR [SUML2] [User] []
		SIM_DATA m_sdSUMF;           //NS_VAR [SUMF] [User] []
		SIM_DATA m_sdFRIC;           //NS_VAR [FRIC] [User] []
		SIM_DATA m_sdDISP;           //NS_VAR [DISP] [User] []
		SIM_DATA m_sdVFUEL;           //NS_VAR [VFUEL] [User] []
		SIM_DATA m_sdVFT;           //NS_VAR [VFT] [User] []
		SIM_DATA m_sdP;           //NS_VAR [P] [User] []
		SIM_DATA m_sdHfg;           //NS_VAR [Hfg] [User] []
		SIM_DATA m_sdsvg;           //NS_VAR [svg] [User] []
		SIM_DATA m_sdTAUS;           //NS_VAR [TAUS] [User] []
		SIM_DATA m_sdHg;           //NS_VAR [Hg] [User] []
		SIM_DATA m_sdSS10;           //NS_VAR [SS10] [User] []
		SIM_DATA m_sdVS10DOT;           //NS_VAR [VS10DOT] [User] []
		SIM_DATA m_sdSS9;           //NS_VAR [SS9] [User] []
		SIM_DATA m_sdVS9DOT;           //NS_VAR [VS9DOT] [User] []
		SIM_DATA m_sdSS8;           //NS_VAR [SS8] [User] []
		SIM_DATA m_sdVS8DOT;           //NS_VAR [VS8DOT] [User] []
		SIM_DATA m_sdSS7;           //NS_VAR [SS7] [User] []
		SIM_DATA m_sdVS7DOT;           //NS_VAR [VS7DOT] [User] []
		SIM_DATA m_sdSS6;           //NS_VAR [SS6] [User] []
		SIM_DATA m_sdVS6DOT;           //NS_VAR [VS6DOT] [User] []
		SIM_DATA m_sdSS5;           //NS_VAR [SS5] [User] []
		SIM_DATA m_sdVS5DOT;           //NS_VAR [VS5DOT] [User] []
		SIM_DATA m_sdSS4;           //NS_VAR [SS4] [User] []
		SIM_DATA m_sdVS4DOT;           //NS_VAR [VS4DOT] [User] []
		SIM_DATA m_sdSS3;           //NS_VAR [SS3] [User] []
		SIM_DATA m_sdVS3DOT;           //NS_VAR [VS3DOT] [User] []
		SIM_DATA m_sdSS2;           //NS_VAR [SS2] [User] []
		SIM_DATA m_sdVS2DOT;           //NS_VAR [VS2DOT] [User] []
		SIM_DATA m_sdSS1;           //NS_VAR [SS1] [User] []
		SIM_DATA m_sdVS1DOT;           //NS_VAR [VS1DOT] [User] []
		SIM_DATA m_sdMC11;           //NS_VAR [MC11] [User] []
		SIM_DATA m_sdMC12;           //NS_VAR [MC12] [User] []
		SIM_DATA m_sdCPC;           //NS_VAR [CPC] [User] []
		SIM_DATA m_sdFR11;           //NS_VAR [FR11] [User] []
		SIM_DATA m_sdFR12;           //NS_VAR [FR12] [User] []
		SIM_DATA m_sdTAUC11;           //NS_VAR [TAUC11] [User] []
		SIM_DATA m_sdTAUC12;           //NS_VAR [TAUC12] [User] []
		SIM_DATA m_sdMC21;           //NS_VAR [MC21] [User] []
		SIM_DATA m_sdMC22;           //NS_VAR [MC22] [User] []
		SIM_DATA m_sdFR21;           //NS_VAR [FR21] [User] []
		SIM_DATA m_sdFR22;           //NS_VAR [FR22] [User] []
		SIM_DATA m_sdTAUC21;           //NS_VAR [TAUC21] [User] []
		SIM_DATA m_sdTAUC22;           //NS_VAR [TAUC22] [User] []
		SIM_DATA m_sdMC31;           //NS_VAR [MC31] [User] []
		SIM_DATA m_sdMC32;           //NS_VAR [MC32] [User] []
		SIM_DATA m_sdFR31;           //NS_VAR [FR31] [User] []
		SIM_DATA m_sdFR32;           //NS_VAR [FR32] [User] []
		SIM_DATA m_sdTAUC31;           //NS_VAR [TAUC31] [User] []
		SIM_DATA m_sdTAUC32;           //NS_VAR [TAUC32] [User] []
		SIM_DATA m_sdMC41;           //NS_VAR [MC41] [User] []
		SIM_DATA m_sdMC42;           //NS_VAR [MC42] [User] []
		SIM_DATA m_sdFR41;           //NS_VAR [FR41] [User] []
		SIM_DATA m_sdFR42;           //NS_VAR [FR42] [User] []
		SIM_DATA m_sdTAUC41;           //NS_VAR [TAUC41] [User] []
		SIM_DATA m_sdTAUC42;           //NS_VAR [TAUC42] [User] []
		SIM_DATA m_sdMC51;           //NS_VAR [MC51] [User] []
		SIM_DATA m_sdMC52;           //NS_VAR [MC52] [User] []
		SIM_DATA m_sdFR51;           //NS_VAR [FR51] [User] []
		SIM_DATA m_sdFR52;           //NS_VAR [FR52] [User] []
		SIM_DATA m_sdTAUC51;           //NS_VAR [TAUC51] [User] []
		SIM_DATA m_sdTAUC52;           //NS_VAR [TAUC52] [User] []
		SIM_DATA m_sdMC61;           //NS_VAR [MC61] [User] []
		SIM_DATA m_sdMC62;           //NS_VAR [MC62] [User] []
		SIM_DATA m_sdFR61;           //NS_VAR [FR61] [User] []
		SIM_DATA m_sdFR62;           //NS_VAR [FR62] [User] []
		SIM_DATA m_sdTAUC61;           //NS_VAR [TAUC61] [User] []
		SIM_DATA m_sdTAUC62;           //NS_VAR [TAUC62] [User] []
		SIM_DATA m_sdMC71;           //NS_VAR [MC71] [User] []
		SIM_DATA m_sdMC72;           //NS_VAR [MC72] [User] []
		SIM_DATA m_sdFR71;           //NS_VAR [FR71] [User] []
		SIM_DATA m_sdFR72;           //NS_VAR [FR72] [User] []
		SIM_DATA m_sdTAUC71;           //NS_VAR [TAUC71] [User] []
		SIM_DATA m_sdTAUC72;           //NS_VAR [TAUC72] [User] []
		SIM_DATA m_sdMC81;           //NS_VAR [MC81] [User] []
		SIM_DATA m_sdMC82;           //NS_VAR [MC82] [User] []
		SIM_DATA m_sdFR81;           //NS_VAR [FR81] [User] []
		SIM_DATA m_sdFR82;           //NS_VAR [FR82] [User] []
		SIM_DATA m_sdTAUC81;           //NS_VAR [TAUC81] [User] []
		SIM_DATA m_sdTAUC82;           //NS_VAR [TAUC82] [User] []
		SIM_DATA m_sdMC91;           //NS_VAR [MC91] [User] []
		SIM_DATA m_sdMC92;           //NS_VAR [MC92] [User] []
		SIM_DATA m_sdFR91;           //NS_VAR [FR91] [User] []
		SIM_DATA m_sdFR92;           //NS_VAR [FR92] [User] []
		SIM_DATA m_sdTAUC91;           //NS_VAR [TAUC91] [User] []
		SIM_DATA m_sdTAUC92;           //NS_VAR [TAUC92] [User] []
		SIM_DATA m_sdMC101;           //NS_VAR [MC101] [User] []
		SIM_DATA m_sdMC102;           //NS_VAR [MC102] [User] []
		SIM_DATA m_sdFR101;           //NS_VAR [FR101] [User] []
		SIM_DATA m_sdFR102;           //NS_VAR [FR102] [User] []
		SIM_DATA m_sdTAUC101;           //NS_VAR [TAUC101] [User] []
		SIM_DATA m_sdTAUC102;           //NS_VAR [TAUC102] [User] []
		SIM_DATA m_sdMP2;           //NS_VAR [MP2] [User] []
		SIM_DATA m_sdTAUP2;           //NS_VAR [TAUP2] [User] []
		SIM_DATA m_sdMT1;           //NS_VAR [MT1] [User] []
		SIM_DATA m_sdTAUT1;           //NS_VAR [TAUT1] [User] []
		SIM_DATA m_sdGAM1;           //NS_VAR [GAM1] [User] []
		SIM_DATA m_sdMP1;           //NS_VAR [MP1] [User] []
		SIM_DATA m_sdTAUP1;           //NS_VAR [TAUP1] [User] []
		SIM_DATA m_sdWC2;           //NS_VAR [WC2] [User] []
		SIM_DATA m_sdMS1;           //NS_VAR [MS1] [User] []
		SIM_DATA m_sdTAUS1;           //NS_VAR [TAUS1] [User] []
		SIM_DATA m_sdGAM2;           //NS_VAR [GAM2] [User] []
		SIM_DATA m_sdGAM3;           //NS_VAR [GAM3] [User] []
		SIM_DATA m_sdMT;           //NS_VAR [MT] [User] []
		SIM_DATA m_sdCPT;           //NS_VAR [CPT] [User] []
		SIM_DATA m_sdMS;           //NS_VAR [MS] [User] []
		SIM_DATA m_sdCPS;           //NS_VAR [CPS] [User] []
		SIM_DATA m_sdHCDOT;           //NS_VAR [HCDOT] [User] []
		SIM_DATA m_sdHTDOT;           //NS_VAR [HTDOT] [User] []
		SIM_DATA m_sdHSDOT;           //NS_VAR [HSDOT] [User] []
		SIM_DATA m_sdHC;           //NS_VAR [HC] [User] []
		SIM_DATA m_sdHC1;           //NS_VAR [HC1] [User] []
		SIM_DATA m_sdHC2;           //NS_VAR [HC2] [User] []
		SIM_DATA m_sdHC3;           //NS_VAR [HC3] [User] []
		SIM_DATA m_sdHC4;           //NS_VAR [HC4] [User] []
		SIM_DATA m_sdHC5;           //NS_VAR [HC5] [User] []
		SIM_DATA m_sdHC6;           //NS_VAR [HC6] [User] []
		SIM_DATA m_sdHC7;           //NS_VAR [HC7] [User] []
		SIM_DATA m_sdHC8;           //NS_VAR [HC8] [User] []
		SIM_DATA m_sdHC9;           //NS_VAR [HC9] [User] []
		SIM_DATA m_sdHC10;           //NS_VAR [HC10] [User] []
		SIM_DATA m_sdHCL;           //NS_VAR [HCL] [User] []
		SIM_DATA m_sdHSHELLS;           //NS_VAR [HSHELLS] [User] []
		SIM_DATA m_sdHTUBES;           //NS_VAR [HTUBES] [User] []
		SIM_DATA m_sdHSHELL;           //NS_VAR [HSHELL] [User] []
		SIM_DATA m_sdHTUBE;           //NS_VAR [HTUBE] [User] []
		SIM_DATA m_sdHP1;           //NS_VAR [HP1] [User] []
		SIM_DATA m_sdHP2;           //NS_VAR [HP2] [User] []
		SIM_DATA m_sdEB;           //NS_VAR [EB] [User] []
		SIM_DATA m_sdROH2A;           //NS_VAR [ROH2A] [User] []
		SIM_DATA m_sdROO2A;           //NS_VAR [ROO2A] [User] []
		SIM_DATA m_sdROH21;           //NS_VAR [ROH21] [User] []
		SIM_DATA m_sdROO21;           //NS_VAR [ROO21] [User] []
		SIM_DATA m_sdXT;           //NS_VAR [XT] [User] []
		SIM_DATA m_sdGH2;           //NS_VAR [GH2] [User] []
		SIM_DATA m_sdGO2;           //NS_VAR [GO2] [User] []
		SIM_DATA m_sdXH210;           //NS_VAR [XH210] [User] []
		SIM_DATA m_sdXO210;           //NS_VAR [XO210] [User] []
		SIM_DATA m_sdXH21;           //NS_VAR [XH21] [User] []
		SIM_DATA m_sdXO21;           //NS_VAR [XO21] [User] []
		SIM_DATA m_sdED1;           //NS_VAR [ED1] [User] []
		SIM_DATA m_sdXTO;           //NS_VAR [XTO] [User] []
		SIM_DATA m_sdG1H;           //NS_VAR [G1H] [User] []
		SIM_DATA m_sdVH1DOT;           //NS_VAR [VH1DOT] [User] []
		SIM_DATA m_sdG1O;           //NS_VAR [G1O] [User] []
		SIM_DATA m_sdVO1DOT;           //NS_VAR [VO1DOT] [User] []
		SIM_DATA m_sdROH22;           //NS_VAR [ROH22] [User] []
		SIM_DATA m_sdROO22;           //NS_VAR [ROO22] [User] []
		SIM_DATA m_sdXH22;           //NS_VAR [XH22] [User] []
		SIM_DATA m_sdXO22;           //NS_VAR [XO22] [User] []
		SIM_DATA m_sdED2;           //NS_VAR [ED2] [User] []
		SIM_DATA m_sdG2H;           //NS_VAR [G2H] [User] []
		SIM_DATA m_sdVH2DOT;           //NS_VAR [VH2DOT] [User] []
		SIM_DATA m_sdG2O;           //NS_VAR [G2O] [User] []
		SIM_DATA m_sdVO2DOT;           //NS_VAR [VO2DOT] [User] []
		SIM_DATA m_sdROH23;           //NS_VAR [ROH23] [User] []
		SIM_DATA m_sdROO23;           //NS_VAR [ROO23] [User] []
		SIM_DATA m_sdXH23;           //NS_VAR [XH23] [User] []
		SIM_DATA m_sdXO23;           //NS_VAR [XO23] [User] []
		SIM_DATA m_sdED3;           //NS_VAR [ED3] [User] []
		SIM_DATA m_sdG3H;           //NS_VAR [G3H] [User] []
		SIM_DATA m_sdVH3DOT;           //NS_VAR [VH3DOT] [User] []
		SIM_DATA m_sdG3O;           //NS_VAR [G3O] [User] []
		SIM_DATA m_sdVO3DOT;           //NS_VAR [VO3DOT] [User] []
		SIM_DATA m_sdROH24;           //NS_VAR [ROH24] [User] []
		SIM_DATA m_sdROO24;           //NS_VAR [ROO24] [User] []
		SIM_DATA m_sdXH24;           //NS_VAR [XH24] [User] []
		SIM_DATA m_sdXO24;           //NS_VAR [XO24] [User] []
		SIM_DATA m_sdED4;           //NS_VAR [ED4] [User] []
		SIM_DATA m_sdG4H;           //NS_VAR [G4H] [User] []
		SIM_DATA m_sdVH4DOT;           //NS_VAR [VH4DOT] [User] []
		SIM_DATA m_sdG4O;           //NS_VAR [G4O] [User] []
		SIM_DATA m_sdVO4DOT;           //NS_VAR [VO4DOT] [User] []
		SIM_DATA m_sdROH25;           //NS_VAR [ROH25] [User] []
		SIM_DATA m_sdROO25;           //NS_VAR [ROO25] [User] []
		SIM_DATA m_sdXH25;           //NS_VAR [XH25] [User] []
		SIM_DATA m_sdXO25;           //NS_VAR [XO25] [User] []
		SIM_DATA m_sdED5;           //NS_VAR [ED5] [User] []
		SIM_DATA m_sdG5H;           //NS_VAR [G5H] [User] []
		SIM_DATA m_sdVH5DOT;           //NS_VAR [VH5DOT] [User] []
		SIM_DATA m_sdG5O;           //NS_VAR [G5O] [User] []
		SIM_DATA m_sdVO5DOT;           //NS_VAR [VO5DOT] [User] []
		SIM_DATA m_sdROH26;           //NS_VAR [ROH26] [User] []
		SIM_DATA m_sdROO26;           //NS_VAR [ROO26] [User] []
		SIM_DATA m_sdXH26;           //NS_VAR [XH26] [User] []
		SIM_DATA m_sdXO26;           //NS_VAR [XO26] [User] []
		SIM_DATA m_sdED6;           //NS_VAR [ED6] [User] []
		SIM_DATA m_sdG6H;           //NS_VAR [G6H] [User] []
		SIM_DATA m_sdVH6DOT;           //NS_VAR [VH6DOT] [User] []
		SIM_DATA m_sdG6O;           //NS_VAR [G6O] [User] []
		SIM_DATA m_sdVO6DOT;           //NS_VAR [VO6DOT] [User] []
		SIM_DATA m_sdROH27;           //NS_VAR [ROH27] [User] []
		SIM_DATA m_sdROO27;           //NS_VAR [ROO27] [User] []
		SIM_DATA m_sdXH27;           //NS_VAR [XH27] [User] []
		SIM_DATA m_sdXO27;           //NS_VAR [XO27] [User] []
		SIM_DATA m_sdED7;           //NS_VAR [ED7] [User] []
		SIM_DATA m_sdG7H;           //NS_VAR [G7H] [User] []
		SIM_DATA m_sdVH7DOT;           //NS_VAR [VH7DOT] [User] []
		SIM_DATA m_sdG7O;           //NS_VAR [G7O] [User] []
		SIM_DATA m_sdVO7DOT;           //NS_VAR [VO7DOT] [User] []
		SIM_DATA m_sdROH28;           //NS_VAR [ROH28] [User] []
		SIM_DATA m_sdROO28;           //NS_VAR [ROO28] [User] []
		SIM_DATA m_sdXH28;           //NS_VAR [XH28] [User] []
		SIM_DATA m_sdXO28;           //NS_VAR [XO28] [User] []
		SIM_DATA m_sdED8;           //NS_VAR [ED8] [User] []
		SIM_DATA m_sdG8H;           //NS_VAR [G8H] [User] []
		SIM_DATA m_sdVH8DOT;           //NS_VAR [VH8DOT] [User] []
		SIM_DATA m_sdG8O;           //NS_VAR [G8O] [User] []
		SIM_DATA m_sdVO8DOT;           //NS_VAR [VO8DOT] [User] []
		SIM_DATA m_sdROH29;           //NS_VAR [ROH29] [User] []
		SIM_DATA m_sdROO29;           //NS_VAR [ROO29] [User] []
		SIM_DATA m_sdXH29;           //NS_VAR [XH29] [User] []
		SIM_DATA m_sdXO29;           //NS_VAR [XO29] [User] []
		SIM_DATA m_sdED9;           //NS_VAR [ED9] [User] []
		SIM_DATA m_sdG9H;           //NS_VAR [G9H] [User] []
		SIM_DATA m_sdVH9DOT;           //NS_VAR [VH9DOT] [User] []
		SIM_DATA m_sdG9O;           //NS_VAR [G9O] [User] []
		SIM_DATA m_sdVO9DOT;           //NS_VAR [VO9DOT] [User] []
		SIM_DATA m_sdROH210;           //NS_VAR [ROH210] [User] []
		SIM_DATA m_sdROO210;           //NS_VAR [ROO210] [User] []
		SIM_DATA m_sdED10;           //NS_VAR [ED10] [User] []
		SIM_DATA m_sdG10H;           //NS_VAR [G10H] [User] []
		SIM_DATA m_sdVH10DOT;           //NS_VAR [VH10DOT] [User] []
		SIM_DATA m_sdG10O;           //NS_VAR [G10O] [User] []
		SIM_DATA m_sdVO10DOT;           //NS_VAR [VO10DOT] [User] []
		SIM_DATA m_sdHPDOT;           //NS_VAR [HPDOT] [User] []
		SIM_DATA m_sdOPDOT;           //NS_VAR [OPDOT] [User] []
		SIM_DATA m_sdVHTOT;           //NS_VAR [VHTOT] [User] []
		SIM_DATA m_sdVOTOT;           //NS_VAR [VOTOT] [User] []
		SIM_DATA m_sdVF;           //NS_VAR [Core Averaged Void Fraction] [Performance] []
		SIM_DATA m_sdPTRIP;           //NS_VAR [PTRIP] [User] []
		SIM_DATA m_sdPSIG;           //NS_VAR [PSIG] [User] []
		SIM_DATA m_sdWMUIN;           //NS_VAR [WMUIN] [User] []
		SIM_DATA m_sdWMUDOT;           //NS_VAR [WMUDOT] [User] []
		SIM_DATA m_sdROW;           //NS_VAR [ROW] [User] []
		SIM_DATA m_sdVFDOT;           //NS_VAR [VFDOT] [User] []
		SIM_DATA m_sdVHDT1;           //NS_VAR [VHDT1] [User] []
		SIM_DATA m_sdVHDT2;           //NS_VAR [VHDT2] [User] []
		SIM_DATA m_sdVODT1;           //NS_VAR [VODT1] [User] []
		SIM_DATA m_sdVODT2;           //NS_VAR [VODT2] [User] []
		SIM_DATA m_sdVPDOT;           //NS_VAR [VPDOT] [User] []
		SIM_DATA m_sdVCTOT;           //NS_VAR [VCTOT] [User] []
		SIM_DATA m_sdCPH;           //NS_VAR [CPH] [User] []
		SIM_DATA m_sdCPO;           //NS_VAR [CPO] [User] []
		SIM_DATA m_sdCPN;           //NS_VAR [CPN] [User] []
		SIM_DATA m_sdT20;           //NS_VAR [T20] [User] []
		SIM_DATA m_sdENH20;           //NS_VAR [ENH20] [User] []
		SIM_DATA m_sdENO20;           //NS_VAR [ENO20] [User] []
		SIM_DATA m_sdENN20;           //NS_VAR [ENN20] [User] []
		SIM_DATA m_sdENH1;           //NS_VAR [ENH1] [User] []
		SIM_DATA m_sdENO1;           //NS_VAR [ENO1] [User] []
		SIM_DATA m_sdENO2;           //NS_VAR [ENO2] [User] []
		SIM_DATA m_sdENN2;           //NS_VAR [ENN2] [User] []
		SIM_DATA m_sdENH5;           //NS_VAR [ENH5] [User] []
		SIM_DATA m_sdENO5;           //NS_VAR [ENO5] [User] []
		SIM_DATA m_sdENN5;           //NS_VAR [ENN5] [User] []
		SIM_DATA m_sdRHY;           //NS_VAR [RHY] [User] []
		SIM_DATA m_sdROX;           //NS_VAR [ROX] [User] []
		SIM_DATA m_sdRN;           //NS_VAR [RN] [User] []
		SIM_DATA m_sdHFH;           //NS_VAR [HFH] [User] []
		SIM_DATA m_sdHFO;           //NS_VAR [HFO] [User] []
		SIM_DATA m_sdHFN;           //NS_VAR [HFN] [User] []
		SIM_DATA m_sdHFOUT;           //NS_VAR [HFOUT] [User] []
		SIM_DATA m_sdCVH;           //NS_VAR [CVH] [User] []
		SIM_DATA m_sdCVO;           //NS_VAR [CVO] [User] []
		SIM_DATA m_sdCVN;           //NS_VAR [CVN] [User] []
		SIM_DATA m_sdMCV;           //NS_VAR [MCV] [User] []
		SIM_DATA m_sdTPDOT;           //NS_VAR [TPDOT] [User] []
		SIM_DATA m_sdMHDOT;           //NS_VAR [MHDOT] [User] []
		SIM_DATA m_sdPHDOT;           //NS_VAR [PHDOT] [User] []
		SIM_DATA m_sdH2F;           //NS_VAR [H2F] [User] []
		SIM_DATA m_sdMODOT;           //NS_VAR [MODOT] [User] []
		SIM_DATA m_sdPODOT;           //NS_VAR [PODOT] [User] []
		SIM_DATA m_sdMNDOT;           //NS_VAR [MNDOT] [User] []
		SIM_DATA m_sdPNDOT;           //NS_VAR [PNDOT] [User] []
		SIM_DATA m_sdRR;           //NS_VAR [RR] [User] []
		SIM_DATA m_sdTEM;           //NS_VAR [TEM] [User] []
		SIM_DATA m_sdTEM2;           //NS_VAR [Coolant Exit Tempereature] [Performance] [C]
		SIM_DATA m_sdTEM3;           //NS_VAR [TEM3] [User] []
		SIM_DATA m_sdTEM4;           //NS_VAR [TEM4] [User] []
		SIM_DATA m_sdVOG;           //NS_VAR [VOG] [User] []
		SIM_DATA m_sdPS;           //NS_VAR [PS] [User] []
		SIM_DATA m_sdELOG;           //NS_VAR [ELOG] [User] []
		SIM_DATA m_sdEPOW;           //NS_VAR [EPOW] [User] []
		SIM_DATA m_sdVGAS;           //NS_VAR [VGAS] [User] []

		//define state variables here
		SIM_DATA *m_sdEN;           //STATE_VAR [EN] [User] []
		SIM_DATA *m_sdD1;           //STATE_VAR [D1] [User] []
		SIM_DATA *m_sdD2;           //STATE_VAR [D2] [User] []
		SIM_DATA *m_sdD3;           //STATE_VAR [D3] [User] []
		SIM_DATA *m_sdD4;           //STATE_VAR [D4] [User] []
		SIM_DATA *m_sdD5;           //STATE_VAR [D5] [User] []
		SIM_DATA *m_sdD6;           //STATE_VAR [D6] [User] []
		SIM_DATA *m_sdETOT;           //STATE_VAR [ETOT] [User] []
		SIM_DATA *m_sdE;           //STATE_VAR [E] [User] []
		SIM_DATA *m_sdTEMP1;           //STATE_VAR [Region 1 Fuel Temperature] [Temperature Profile] [C]
		SIM_DATA *m_sdVFUEL1;           //STATE_VAR [VFUEL1] [User] []
		SIM_DATA *m_sdTL11;           //STATE_VAR [TL11] [User] []
		SIM_DATA *m_sdVL11;           //STATE_VAR [VL11] [User] []
		SIM_DATA *m_sdTL12;           //STATE_VAR [Region 1 Boundary Layer Exit Temperature] [Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL12;           //STATE_VAR [VL12] [User] []
		SIM_DATA *m_sdTW1;           //STATE_VAR [TW1] [User] []
		SIM_DATA *m_sdTL21;           //STATE_VAR [TL21] [User] []
		SIM_DATA *m_sdVL21;           //STATE_VAR [VL21] [User] []
		SIM_DATA *m_sdTL22;           //STATE_VAR [Region 2 Boundary Layer Exit Temperature] [Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL22;           //STATE_VAR [VL22] [User] []
		SIM_DATA *m_sdTW2;           //STATE_VAR [TW2] [User] []
		SIM_DATA *m_sdTL31;           //STATE_VAR [TL31] [User] []
		SIM_DATA *m_sdVL31;           //STATE_VAR [VL31] [User] []
		SIM_DATA *m_sdTL32;           //STATE_VAR [Region 3 Boundary Layer Exit Temperature] [Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL32;           //STATE_VAR [VL32] [User] []
		SIM_DATA *m_sdTW3;           //STATE_VAR [TW3] [User] []
		SIM_DATA *m_sdTL41;           //STATE_VAR [TL41] [User] []
		SIM_DATA *m_sdVL41;           //STATE_VAR [VL41] [User] []
		SIM_DATA *m_sdTL42;           //STATE_VAR [Region 4 Boundary Layer Exit Temperature] [Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL42;           //STATE_VAR [VL42] [User] []
		SIM_DATA *m_sdTW4;           //STATE_VAR [TW4] [User] []
		SIM_DATA *m_sdTL51;           //STATE_VAR [TL51] [User] []
		SIM_DATA *m_sdVL51;           //STATE_VAR [VL51] [User] []
		SIM_DATA *m_sdTL52;           //STATE_VAR [Region 5 Boundary Layer Exit Temperature] [Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL52;           //STATE_VAR [VL52] [User] []
		SIM_DATA *m_sdTW5;           //STATE_VAR [TW5] [User] []
		SIM_DATA *m_sdTL61;           //STATE_VAR [TL61] [User] []
		SIM_DATA *m_sdVL61;           //STATE_VAR [VL61] [User] []
		SIM_DATA *m_sdTL62;           //STATE_VAR [Region 6 Boundary Layer Exit Temperature] [Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL62;           //STATE_VAR [VL62] [User] []
		SIM_DATA *m_sdTW6;           //STATE_VAR [TW6] [User] []
		SIM_DATA *m_sdTL71;           //STATE_VAR [TL71] [User] []
		SIM_DATA *m_sdVL71;           //STATE_VAR [VL71] [User] []
		SIM_DATA *m_sdTL72;           //STATE_VAR [Region 7 Boundary Layer Exit Temperature] [Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL72;           //STATE_VAR [VL72] [User] []
		SIM_DATA *m_sdTW7;           //STATE_VAR [TW7] [User] []
		SIM_DATA *m_sdTL81;           //STATE_VAR [TL81] [User] []
		SIM_DATA *m_sdVL81;           //STATE_VAR [VL81] [User] []
		SIM_DATA *m_sdTL82;           //STATE_VAR [Region 8 Boundary Layer Exit Temperature] [Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL82;           //STATE_VAR [VL82] [User] []
		SIM_DATA *m_sdTW8;           //STATE_VAR [TW8] [User] []
		SIM_DATA *m_sdTL91;           //STATE_VAR [TL91] [User] []
		SIM_DATA *m_sdVL91;           //STATE_VAR [VL91] [User] []
		SIM_DATA *m_sdTL92;           //STATE_VAR [Region 9 Boundary Layer Exit Temperature] [Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL92;           //STATE_VAR [VL92] [User] []
		SIM_DATA *m_sdTW9;           //STATE_VAR [TW9] [User] []
		SIM_DATA *m_sdTL101;           //STATE_VAR [TL101] [User] []
		SIM_DATA *m_sdVL101;           //STATE_VAR [VL101] [User] []
		SIM_DATA *m_sdTL102;           //STATE_VAR [Region 10 Boundary Layer Exit Temperature] [Boundary Layer Temperature Profile] [C]
		SIM_DATA *m_sdVL102;           //STATE_VAR [VL102] [User] []
		SIM_DATA *m_sdTW10;           //STATE_VAR [TW10] [User] []
		SIM_DATA *m_sdTEMP2;           //STATE_VAR [Region 2 Fuel Temperature] [Temperature Profile] [C]
		SIM_DATA *m_sdVFUEL2;           //STATE_VAR [VFUEL2] [User] []
		SIM_DATA *m_sdTEMP3;           //STATE_VAR [Region 3 Fuel Temperature] [Temperature Profile] [C]
		SIM_DATA *m_sdVFUEL3;           //STATE_VAR [VFUEL3] [User] []
		SIM_DATA *m_sdTEMP4;           //STATE_VAR [Region 4 Fuel Temperature] [Temperature Profile] [C]
		SIM_DATA *m_sdVFUEL4;           //STATE_VAR [VFUEL4] [User] []
		SIM_DATA *m_sdTEMP5;           //STATE_VAR [Region 5 Fuel Temperature] [Temperature Profile] [C]
		SIM_DATA *m_sdVFUEL5;           //STATE_VAR [VFUEL5] [User] []
		SIM_DATA *m_sdTEMP6;           //STATE_VAR [Region 6 Fuel Temperature] [Temperature Profile] [C]
		SIM_DATA *m_sdVFUEL6;           //STATE_VAR [VFUEL6] [User] []
		SIM_DATA *m_sdTEMP7;           //STATE_VAR [Region 7 Fuel Temperature] [Temperature Profile] [C]
		SIM_DATA *m_sdVFUEL7;           //STATE_VAR [VFUEL7] [User] []
		SIM_DATA *m_sdTEMP8;           //STATE_VAR [Region 8 Fuel Temperature] [Temperature Profile] [C]
		SIM_DATA *m_sdVFUEL8;           //STATE_VAR [VFUEL8] [User] []
		SIM_DATA *m_sdTEMP9;           //STATE_VAR [Region 9 Fuel Temperature] [Temperature Profile] [C]
		SIM_DATA *m_sdVFUEL9;           //STATE_VAR [VFUEL9] [User] []
		SIM_DATA *m_sdTEMP10;           //STATE_VAR [Region 10 Fuel Temperature] [Temperature Profile] [C]
		SIM_DATA *m_sdVFUEL10;           //STATE_VAR [VFUEL10] [User] []
		SIM_DATA *m_sdWF;           //STATE_VAR [WF] [User] []
		SIM_DATA *m_sdVS10;           //STATE_VAR [Region 10 Steam Volume] [Steam Volume] [m3]
		SIM_DATA *m_sdVS9;           //STATE_VAR [Region 9 Steam Volume] [Steam Volume] [m3]
		SIM_DATA *m_sdVS8;           //STATE_VAR [Region 8 Steam Volume] [Steam Volume] [m3]
		SIM_DATA *m_sdVS7;           //STATE_VAR [Region 7 Steam Volume] [Steam Volume] [m3]
		SIM_DATA *m_sdVS6;           //STATE_VAR [Region 6 Steam Volume] [Steam Volume] [m3]
		SIM_DATA *m_sdVS5;           //STATE_VAR [Region 5 Steam Volume] [Steam Volume] [m3]
		SIM_DATA *m_sdVS4;           //STATE_VAR [Region 4 Steam Volume] [Steam Volume] [m3]
		SIM_DATA *m_sdVS3;           //STATE_VAR [Region 3 Steam Volume] [Steam Volume] [m3]
		SIM_DATA *m_sdVS2;           //STATE_VAR [Region 2 Steam Volume] [Steam Volume] [m3]
		SIM_DATA *m_sdVS1;           //STATE_VAR [Region 1 Steam Volume] [Steam Volume] [m3]
		SIM_DATA *m_sdTC11;           //STATE_VAR [TC11] [User] []
		SIM_DATA *m_sdTC12;           //STATE_VAR [Region 1 Coolant Exit Temperature] [Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC21;           //STATE_VAR [TC21] [User] []
		SIM_DATA *m_sdTC22;           //STATE_VAR [Region 2 Coolant Exit Temperature] [Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC31;           //STATE_VAR [TC31] [User] []
		SIM_DATA *m_sdTC32;           //STATE_VAR [Region 3 Coolant Exit Temperature] [Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC41;           //STATE_VAR [TC41] [User] []
		SIM_DATA *m_sdTC42;           //STATE_VAR [Region 4 Coolant Exit Temperature] [Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC51;           //STATE_VAR [TC51] [User] []
		SIM_DATA *m_sdTC52;           //STATE_VAR [Region 5 Coolant Exit Temperature] [Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC61;           //STATE_VAR [TC61] [User] []
		SIM_DATA *m_sdTC62;           //STATE_VAR [Region 6 Coolant Exit Temperature] [Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC71;           //STATE_VAR [TC71] [User] []
		SIM_DATA *m_sdTC72;           //STATE_VAR [Region 7 Coolant Exit Temperature] [Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC81;           //STATE_VAR [TC81] [User] []
		SIM_DATA *m_sdTC82;           //STATE_VAR [Region 8 Coolant Exit Temperature] [Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC91;           //STATE_VAR [TC91] [User] []
		SIM_DATA *m_sdTC92;           //STATE_VAR [Region 9 Coolant Exit Temperature] [Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTC101;           //STATE_VAR [TC101] [User] []
		SIM_DATA *m_sdTC102;           //STATE_VAR [Region 10 Coolant Exit Temperature] [Coolant Temperature Profile] [C]
		SIM_DATA *m_sdTP2;           //STATE_VAR [TP2] [User] []
		SIM_DATA *m_sdTT1;           //STATE_VAR [TT1] [User] []
		SIM_DATA *m_sdTT2;           //STATE_VAR [TT2] [User] []
		SIM_DATA *m_sdTS1;           //STATE_VAR [TS1] [User] []
		SIM_DATA *m_sdTS2;           //STATE_VAR [TS2] [User] []
		SIM_DATA *m_sdTT;           //STATE_VAR [TT] [User] []
		SIM_DATA *m_sdTS;           //STATE_VAR [TS] [User] []
		SIM_DATA *m_sdHSOUT;           //STATE_VAR [HSOUT] [User] []
		SIM_DATA *m_sdHTOUT;           //STATE_VAR [HTOUT] [User] []
		SIM_DATA *m_sdHCOUT;           //STATE_VAR [HCOUT] [User] []
		SIM_DATA *m_sdMDH21;           //STATE_VAR [MDH21] [User] []
		SIM_DATA *m_sdMDO21;           //STATE_VAR [MDO21] [User] []
		SIM_DATA *m_sdVGH1;           //STATE_VAR [Region 1 H2 Volume] [H2 Volume Profile] [m3]
		SIM_DATA *m_sdVGO1;           //STATE_VAR [Region 1 O2 Volume] [O2 Volume Profile] [m3]
		SIM_DATA *m_sdMDH22;           //STATE_VAR [MDH22] [User] []
		SIM_DATA *m_sdMDO22;           //STATE_VAR [MDO22] [User] []
		SIM_DATA *m_sdVGH2;           //STATE_VAR [Region 2 H2 Volume] [H2 Volume Profile] [m3]
		SIM_DATA *m_sdVGO2;           //STATE_VAR [Region 2 O2 Volume] [O2 Volume Profile] [m3]
		SIM_DATA *m_sdMDH23;           //STATE_VAR [MDH23] [User] []
		SIM_DATA *m_sdMDO23;           //STATE_VAR [MDO23] [User] []
		SIM_DATA *m_sdVGH3;           //STATE_VAR [Region 3 H2 Volume] [H2 Volume Profile] [m3]
		SIM_DATA *m_sdVGO3;           //STATE_VAR [Region 3 O2 Volume] [O2 Volume Profile] [m3]
		SIM_DATA *m_sdMDH24;           //STATE_VAR [MDH24] [User] []
		SIM_DATA *m_sdMDO24;           //STATE_VAR [MDO24] [User] []
		SIM_DATA *m_sdVGH4;           //STATE_VAR [Region 4 H2 Volume] [H2 Volume Profile] [m3]
		SIM_DATA *m_sdVGO4;           //STATE_VAR [Region 4 O2 Volume] [O2 Volume Profile] [m3]
		SIM_DATA *m_sdMDH25;           //STATE_VAR [MDH25] [User] []
		SIM_DATA *m_sdMDO25;           //STATE_VAR [MDO25] [User] []
		SIM_DATA *m_sdVGH5;           //STATE_VAR [Region 5 H2 Volume] [H2 Volume Profile] [m3]
		SIM_DATA *m_sdVGO5;           //STATE_VAR [Region 5 O2 Volume] [O2 Volume Profile] [m3]
		SIM_DATA *m_sdMDH26;           //STATE_VAR [MDH26] [User] []
		SIM_DATA *m_sdMDO26;           //STATE_VAR [MDO26] [User] []
		SIM_DATA *m_sdVGH6;           //STATE_VAR [Region 6 H2 Volume] [H2 Volume Profile] [m3]
		SIM_DATA *m_sdVGO6;           //STATE_VAR [Region 6 O2 Volume] [O2 Volume Profile] [m3]
		SIM_DATA *m_sdMDH27;           //STATE_VAR [MDH27] [User] []
		SIM_DATA *m_sdMDO27;           //STATE_VAR [MDO27] [User] []
		SIM_DATA *m_sdVGH7;           //STATE_VAR [Region 7 H2 Volume] [H2 Volume Profile] [m3]
		SIM_DATA *m_sdVGO7;           //STATE_VAR [Region 7 O2 Volume] [O2 Volume Profile] [m3]
		SIM_DATA *m_sdMDH28;           //STATE_VAR [MDH28] [User] []
		SIM_DATA *m_sdMDO28;           //STATE_VAR [MDO28] [User] []
		SIM_DATA *m_sdVGH8;           //STATE_VAR [Region 8 H2 Volume] [H2 Volume Profile] [m3]
		SIM_DATA *m_sdVGO8;           //STATE_VAR [Region 8 O2 Volume] [O2 Volume Profile] [m3]
		SIM_DATA *m_sdMDH29;           //STATE_VAR [MDH29] [User] []
		SIM_DATA *m_sdMDO29;           //STATE_VAR [MDO29] [User] []
		SIM_DATA *m_sdVGH9;           //STATE_VAR [Region 9 H2 Volume] [H2 Volume Profile] [m3]
		SIM_DATA *m_sdVGO9;           //STATE_VAR [Region 9 O2 Volume] [O2 Volume Profile] [m3]
		SIM_DATA *m_sdMDH210;           //STATE_VAR [MDH210] [User] []
		SIM_DATA *m_sdMDO210;           //STATE_VAR [MDO210] [User] []
		SIM_DATA *m_sdVGH10;           //STATE_VAR [Region 10 H2 Volume] [H2 Volume Profile] [m3]
		SIM_DATA *m_sdVGO10;           //STATE_VAR [Region 10 O2 Volume] [O2 Volume Profile] [m3]
		SIM_DATA *m_sdHP;           //STATE_VAR [HP] [User] []
		SIM_DATA *m_sdOP;           //STATE_VAR [OP] [User] []
		SIM_DATA *m_sdVOGO;           //STATE_VAR [VOGO] [User] []
		SIM_DATA *m_sdVNI;           //STATE_VAR [VNI] [User] []
		SIM_DATA *m_sdWMU;           //STATE_VAR [WMU] [User] []
		SIM_DATA *m_sdVP;           //STATE_VAR [VP] [User] []
		SIM_DATA *m_sdTP;           //STATE_VAR [TP] [User] []
		SIM_DATA *m_sdHEATIN;           //STATE_VAR [HEATIN] [User] []
		SIM_DATA *m_sdHEATOUT;           //STATE_VAR [HEATOUT] [User] []
		SIM_DATA *m_sdUP;           //STATE_VAR [UP] [User] []
		SIM_DATA *m_sdWORK;           //STATE_VAR [WORK] [User] []
		SIM_DATA *m_sdMHY;           //STATE_VAR [MHY] [User] []
		SIM_DATA *m_sdPH;           //STATE_VAR [PH] [User] []
		SIM_DATA *m_sdMOX;           //STATE_VAR [MOX] [User] []
		SIM_DATA *m_sdPO;           //STATE_VAR [PO] [User] []
		SIM_DATA *m_sdMN;           //STATE_VAR [MN] [User] []
		SIM_DATA *m_sdPN;           //STATE_VAR [PN] [User] []
	private:
		SIM_DATA m_sdConstBase;
		//define CONST here
		SIM_DATA m_sdTKW;           //CONST [Thermal Conductivity] [Physical Parameters] [MW/mC]
		SIM_DATA m_sdTB;           //CONST [] [Constant] []
		SIM_DATA m_sdRG;           //CONST [] [Constant] []
		SIM_DATA m_sdHM;           //CONST [] [Constant] []
		SIM_DATA m_sdOM;           //CONST [] [Constant] []
		SIM_DATA m_sdNM;           //CONST [] [Constant] []
		SIM_DATA m_sdPI;           //CONST [] [Constant] []
		SIM_DATA m_sdUM;           //CONST [] [Constant] []
		SIM_DATA m_sdAN;           //CONST [] [Constant] []
		SIM_DATA m_sdkB;           //CONST [] [Constant] []
		SIM_DATA m_sdnmass;           //CONST [] [Constant] []
		SIM_DATA m_sdAL1;           //CONST [] [Constant] [] stability
		SIM_DATA m_sdF1;           //CONST [] [Constant] [] stability
		SIM_DATA m_sdAL2;           //CONST [] [Constant] [] stability
		SIM_DATA m_sdF2;           //CONST [] [Constant] [] stability
		SIM_DATA m_sdAL3;           //CONST [] [Constant] [] stability
		SIM_DATA m_sdF3;           //CONST [] [Constant] [] stability
		SIM_DATA m_sdAL4;           //CONST [] [Constant] [] stability
		SIM_DATA m_sdF4;           //CONST [] [Constant] [] stability
		SIM_DATA m_sdAL5;           //CONST [] [Constant] [] stability
		SIM_DATA m_sdF5;           //CONST [] [Constant] [] stability
		SIM_DATA m_sdAL6;           //CONST [] [Constant] [] stability
		SIM_DATA m_sdF6;           //CONST [] [Constant] [] stability
		SIM_DATA m_sdalpha;           //CONST [Isobaric Compressibility of Fuel] [Physical Parameters] [1/C]
		SIM_DATA m_sdTKF;           //CONST [Thermal Conductivity of Fuel] [Physical Parameters] [MW/mC]
		SIM_DATA m_sdPr;           //CONST [Prandtl number for fuel] [Physical Parameters] []
		SIM_DATA m_sdbta;           //CONST [Expansion Coefficient of Fuel] [Physical Parameters] [1/C]
		SIM_DATA m_sdkinvis;           //CONST [Kinematic Viscosity of Fuel] [Physical Parameters] []
		SIM_DATA m_sdTHDIFF;           //CONST [Thermal Diffusivity of Fuel] [Physical Parameters] [m2/s]
		SIM_DATA m_sdCV;           //CONST [Specific Heat of Fuel] [Physical Parameters] [MJ/(CKg)]
		SIM_DATA m_sdPr2;           //CONST [Prandtl Number for coolant] [Physical Parameters] []
		SIM_DATA m_sdV0;           //CONST [Initial Core Volume] [Core Configuration] [m3]
		SIM_DATA m_sdHCORE;           //CONST [Initial Core Height] [Core Configuration] [m]
		SIM_DATA m_sdCSA;           //CONST [Cooling Surface Area] [Core Configuration] [m2]
		SIM_DATA m_sdVP0;           //CONST [Initial Plenum Volume] [Core Configuration] [m3]
		SIM_DATA m_sdCCR;           //CONST [Cooling tube radius] [Core Configuration] [m]
		SIM_DATA m_sdAREAHT;           //CONST [Total Core Cooling Surface] [Core Configuration] [m2]
		SIM_DATA m_sdMW;           //CONST [Mass of cooling wall] [Core Configuration] [kg]
		SIM_DATA m_sdCPW;           //CONST [Specific Heat of cooling wall] [Core Configuration] [Mj/C/kg]
		SIM_DATA m_sdALF;           //CONST [Core Averaged Temperature Coefficient of Reactivity] [Reactivity Parameters] [$/C] stability
		SIM_DATA m_sdPHI;           //CONST [Core Averaged Void Coefficient of Reactivity] [Reactivity Parameters] [$] stability
		SIM_DATA m_sdI10;           //CONST [Importance Factor for Region 10] [Reactivity Parameters] []
		SIM_DATA m_sdI9;           //CONST [Importance Factor for Region 9] [Reactivity Parameters] []
		SIM_DATA m_sdI8;           //CONST [Importance Factor for Region 8] [Reactivity Parameters] []
		SIM_DATA m_sdI7;           //CONST [Importance Factor for Region 7] [Reactivity Parameters] []
		SIM_DATA m_sdI6;           //CONST [Importance Factor for Region 6] [Reactivity Parameters] []
		SIM_DATA m_sdI5;           //CONST [Importance Factor for Region 5] [Reactivity Parameters] []
		SIM_DATA m_sdI4;           //CONST [Importance Factor for Region 4] [Reactivity Parameters] []
		SIM_DATA m_sdI3;           //CONST [Importance Factor for Region 3] [Reactivity Parameters] []
		SIM_DATA m_sdI2;           //CONST [Importance Factor for Region 2] [Reactivity Parameters] []
		SIM_DATA m_sdI1;           //CONST [Importance Factor for Region 1] [Reactivity Parameters] []
		SIM_DATA m_sdFRA10;           //CONST [Fission Fraction for Region 10] [Reactivity Parameters] []
		SIM_DATA m_sdFRA9;           //CONST [Fission Fraction for Region 9] [Reactivity Parameters] []
		SIM_DATA m_sdFRA8;           //CONST [Fission Fraction for Region 8] [Reactivity Parameters] []
		SIM_DATA m_sdFRA7;           //CONST [Fission Fraction for Region 7] [Reactivity Parameters] []
		SIM_DATA m_sdFRA6;           //CONST [Fission Fraction for Region 6] [Reactivity Parameters] []
		SIM_DATA m_sdFRA5;           //CONST [Fission Fraction for Region 5] [Reactivity Parameters] []
		SIM_DATA m_sdFRA4;           //CONST [Fission Fraction for Region 4] [Reactivity Parameters] []
		SIM_DATA m_sdFRA3;           //CONST [Fission Fraction for Region 3] [Reactivity Parameters] []
		SIM_DATA m_sdFRA2;           //CONST [Fission Fraction for Region 2] [Reactivity Parameters] []
		SIM_DATA m_sdFRA1;           //CONST [Fission Fraction for Region 1] [Reactivity Parameters] []
		SIM_DATA m_sdMNT;           //CONST [Mean Neutron Generation Time] [Reactivity Parameters] [s] stability
		SIM_DATA m_sdBETA;           //CONST [Delayed Neutron Fraction] [Reactivity Parameters] [] stability
		SIM_DATA m_sdTAU;           //CONST [Average Gas Bubble Transit Time] [Reactivity Parameters] [s] stability
		SIM_DATA m_sdT0;           //CONST [Initial Fuel Temperature] [Operational Parameters] [C]
		SIM_DATA m_sdTC0;           //CONST [Initial Coolant Temperature] [Operational Parameters] [C]
		SIM_DATA m_sdP0;           //CONST [Plenum Inlet Pressure] [Operational Parameters] [pa]
		SIM_DATA m_sdRRTE;           //CONST [Rate of Reactivity Insertion] [Operational Parameters] [$/s]
		SIM_DATA m_sdFLAG;           //CONST [Point-in-time-of reactivity insertion] [Operational Parameters] [s]
		SIM_DATA m_sdRmax;           //CONST [Total Reactivity Insertion] [Operational Parameters] [$]
		SIM_DATA m_sdWCR;           //CONST [Coolant Mass Flow Rate] [Operational Parameters] [kg/s]
		SIM_DATA m_sdMCLUMP;           //CONST [] [Constant] []
		SIM_DATA m_sdFE;           //CONST [Fuel Enrichment] [Operational Parameters] []
		SIM_DATA m_sdFC;           //CONST [Uranium Concentration of Fuel] [Operational Parameters] [g/l]
		SIM_DATA m_sdA;           //CONST [Initial Power] [Reactivity Parameters] [$]
		SIM_DATA m_sdQ0;           //CONST [Intrinsic Neutron Source] [Operational Parameters] [s-1]
		SIM_DATA m_sdEN0;           //CONST [] [Constant] []
		SIM_DATA m_sdTMAX;           //CONST [] [Constant] []
		SIM_DATA m_sdNN;           //CONST [] [Constant] []
		SIM_DATA m_sdscale;           //CONST [] [Constant] []
		SIM_DATA m_sdAC;           //CONST [] [Constant] []
		SIM_DATA m_sdBL;           //CONST [] [Constant] []
		SIM_DATA m_sdAL;           //CONST [] [Constant] []
		SIM_DATA m_sdVLAYER;           //CONST [] [Constant] []
		SIM_DATA m_sdEM;           //CONST [] [Constant] []
		SIM_DATA m_sdELM;           //CONST [] [Constant] []
		SIM_DATA m_sdLI;           //CONST [] [Constant] []
		SIM_DATA m_sdCTR;           //CONST [] [Constant] []
		SIM_DATA m_sdALI;           //CONST [] [Constant] []
		SIM_DATA m_sdALO;           //CONST [] [Constant] []
		SIM_DATA m_sdVL;           //CONST [] [Constant] []
		SIM_DATA m_sdAK;           //CONST [] [Constant] []
		SIM_DATA m_sdAK2;           //CONST [] [Constant] []
		SIM_DATA m_sdMH2;           //CONST [] [Constant] []
		SIM_DATA m_sdMO2;           //CONST [] [Constant] []
		SIM_DATA m_sdTAU2;           //CONST [] [Constant] []
		SIM_DATA m_sdBR1;           //CONST [] [Constant] []
		SIM_DATA m_sdBR2;           //CONST [] [Constant] []
		SIM_DATA m_sdBR3;           //CONST [] [Constant] []
		SIM_DATA m_sdBR4;           //CONST [] [Constant] []
		SIM_DATA m_sdBR5;           //CONST [] [Constant] []
		SIM_DATA m_sdBR6;           //CONST [] [Constant] []
		SIM_DATA m_sdBR7;           //CONST [] [Constant] []
		SIM_DATA m_sdBR8;           //CONST [] [Constant] []
		SIM_DATA m_sdBR9;           //CONST [] [Constant] []
		SIM_DATA m_sdBR10;           //CONST [] [Constant] []
		SIM_DATA m_sdTC1IN;           //CONST [] [Constant] []
		SIM_DATA m_sdC101;           //CONST [] [Constant] []
		SIM_DATA m_sdTS1IN;           //CONST [] [Constant] []
		SIM_DATA m_sdAIR;           //CONST [] [Constant] []
		SIM_DATA m_sdRNI;           //CONST [] [Constant] []
		SIM_DATA m_sdROI;           //CONST [] [Constant] []
	};
}

